interface IitemTiles {
	[key: string]: string
	AMULET_AMETHYST: string;
	AMULET_ARTEFACT_AIR: string;
	AMULET_ARTEFACT_BLOODLUST: string;
	AMULET_ARTEFACT_BROOCH_OF_SHIELDING: string;
	AMULET_ARTEFACT_CEKUGOB: string;
	AMULET_ARTEFACT_FINGER: string;
	AMULET_ARTEFACT_FOUR_WINDS: string;
	AMULET_ARTEFACT_VITALITY: string;
	AMULET_BERYL: string;
	AMULET_BLUE: string;
	AMULET_BONE: string;
	AMULET_BRASS: string;
	AMULET_BRONZE: string;
	AMULET_CABOCHON: string;
	AMULET_CAMEO: string;
	AMULET_CITRINE: string;
	AMULET_COPPER: string;
	AMULET_DIAMOND: string;
	AMULET_EMERALD: string;
	AMULET_FILIGREE: string;
	AMULET_FLOURESCENT: string;
	AMULET_GARNET: string;
	AMULET_GOLDEN: string;
	AMULET_ACROBAT: string;
	AMULET_FAITH: string;
	AMULET_GOURMAND: string;
	AMULET_HARM: string;
	AMULET_INACCURACY: string;
	AMULET_M_REGENERATION: string;
	AMULET_RAGE: string;
	AMULET_REFLECTION: string;
	AMULET_REGENERATION: string;
	AMULET_SPIRIT: string;
	AMULET_JADE: string;
	AMULET_JASPER: string;
	AMULET_LAPIS_LAZULI: string;
	AMULET_MALACHITE: string;
	AMULET_PEARL: string;
	AMULET_PERIDOT: string;
	AMULET_PLATINUM: string;
	AMULET_RANDARTS_AZURE: string;
	AMULET_RANDARTS_CLUSTER: string;
	AMULET_RANDARTS_DROP: string;
	AMULET_RANDARTS_KNOT: string;
	AMULET_RANDARTS_SCARAB: string;
	AMULET_RANDARTS_SKULL: string;
	AMULET_RANDARTS_SPIDER: string;
	AMULET_RANDARTS_SUN: string;
	AMULET_RUBY: string;
	AMULET_SAPPHIRE: string;
	AMULET_SILVER: string;
	AMULET_SOAPSTONE: string;
	AMULET_STEEL: string;
	AMULET_ZIRCONIUM: string;
	ARMOUR_ACID_DRAGON_ARMOUR: string;
	ARMOUR_ANIMAL_SKIN1: string;
	ARMOUR_ANIMAL_SKIN2: string;
	ARMOUR_ANIMAL_SKIN3: string;
	ARMOUR_ARTEFACT_ALCHEMIST: string;
	ARMOUR_ARTEFACT_ASSASSIN: string;
	ARMOUR_ARTEFACT_AUGMENTATION: string;
	ARMOUR_ARTEFACT_BEAR: string;
	ARMOUR_ARTEFACT_BK_BARDING: string;
	ARMOUR_ARTEFACT_BULLSEYE: string;
	ARMOUR_ARTEFACT_CLOUDS: string;
	ARMOUR_ARTEFACT_DRAGONMASK: string;
	ARMOUR_ARTEFACT_DRAGONSKIN: string;
	ARMOUR_ARTEFACT_DRAGON_KING: string;
	ARMOUR_ARTEFACT_DYROVEPREVA: string;
	ARMOUR_ARTEFACT_ETERNAL_TORMENT: string;
	ARMOUR_ARTEFACT_ETHERIC_CAGE: string;
	ARMOUR_ARTEFACT_FAERIE: string;
	ARMOUR_ARTEFACT_FENCER: string;
	ARMOUR_ARTEFACT_FLASH: string;
	ARMOUR_ARTEFACT_FOLLY: string;
	ARMOUR_ARTEFACT_GONG: string;
	ARMOUR_ARTEFACT_HIGH_COUNCIL: string;
	ARMOUR_ARTEFACT_IGNORANCE: string;
	ARMOUR_ARTEFACT_KRYIAS: string;
	ARMOUR_ARTEFACT_LEAR: string;
	ARMOUR_ARTEFACT_LIGHTNING_SCALES: string;
	ARMOUR_ARTEFACT_MAXWELL: string;
	ARMOUR_ARTEFACT_MISFORTUNE: string;
	ARMOUR_ARTEFACT_MOON_TROLL_LEATHER_ARMOUR: string;
	ARMOUR_ARTEFACT_NIGHT: string;
	ARMOUR_ARTEFACT_ORANGE_CRYSTAL: string;
	ARMOUR_ARTEFACT_PONDERING: string;
	ARMOUR_ARTEFACT_RATSKIN_CLOAK: string;
	ARMOUR_ARTEFACT_RESISTANCE: string;
	ARMOUR_ARTEFACT_SALAMANDER: string;
	ARMOUR_ARTEFACT_SPIDER: string;
	ARMOUR_ARTEFACT_STARLIGHT: string;
	ARMOUR_ARTEFACT_TALOS: string;
	ARMOUR_ARTEFACT_THIEF: string;
	ARMOUR_ARTEFACT_VINES: string;
	ARMOUR_ARTEFACT_WAR: string;
	ARMOUR_ARTEFACT_WARLOCK: string;
	ARMOUR_ARTEFACT_ZHOR: string;
	ARMOUR_BARDINGS_CENTAUR_BLUE: string;
	ARMOUR_BARDINGS_CENTAUR_MAGENTA: string;
	ARMOUR_BARDINGS_CENTAUR_METAL: string;
	ARMOUR_BARDINGS_CENTAUR_RED: string;
	ARMOUR_BARDINGS_NAGA_BLUE: string;
	ARMOUR_BARDINGS_NAGA_MAGENTA: string;
	ARMOUR_BARDINGS_NAGA_METAL: string;
	ARMOUR_BARDINGS_NAGA_RED: string;
	ARMOUR_BLUE_DRAGON_SCALE_MAIL: string;
	ARMOUR_BOOTS1_BROWN: string;
	ARMOUR_BOOTS2_JACKBOOTS: string;
	ARMOUR_BOOTS3_STRIPE: string;
	ARMOUR_BOOTS4_GREEN: string;
	ARMOUR_BRANDS_ARCHERY: string;
	ARMOUR_BRANDS_ARCHMAGI: string;
	ARMOUR_BRANDS_CLOUD_IMMUNE: string;
	ARMOUR_BRANDS_COLD_RES: string;
	ARMOUR_BRANDS_DEXTERITY: string;
	ARMOUR_BRANDS_FIRE_RES: string;
	ARMOUR_BRANDS_FLYING: string;
	ARMOUR_BRANDS_INTELLIGENCE: string;
	ARMOUR_BRANDS_INVISIBILITY: string;
	ARMOUR_BRANDS_JUMPING: string;
	ARMOUR_BRANDS_MAGIC_RES: string;
	ARMOUR_BRANDS_POISON_RES: string;
	ARMOUR_BRANDS_PONDEROUS: string;
	ARMOUR_BRANDS_POSITIVE_ENERGY: string;
	ARMOUR_BRANDS_PRESERVATION: string;
	ARMOUR_BRANDS_PROTECTION: string;
	ARMOUR_BRANDS_REFLECTION: string;
	ARMOUR_BRANDS_REPULSION: string;
	ARMOUR_BRANDS_RESISTANCE: string;
	ARMOUR_BRANDS_RUNNING: string;
	ARMOUR_BRANDS_SEE_INVIS: string;
	ARMOUR_BRANDS_SPIRIT: string;
	ARMOUR_BRANDS_STEALTH: string;
	ARMOUR_BRANDS_STRENGTH: string;
	ARMOUR_CHAIN_MAIL1: string;
	ARMOUR_CHAIN_MAIL2: string;
	ARMOUR_CHAIN_MAIL3: string;
	ARMOUR_CLOAK1_LEATHER: string;
	ARMOUR_CLOAK2: string;
	ARMOUR_CLOAK3: string;
	ARMOUR_CLOAK4: string;
	ARMOUR_CRYSTAL_PLATE: string;
	ARMOUR_CRYSTAL_PLATE2: string;
	ARMOUR_CRYSTAL_PLATE3: string;
	ARMOUR_DEEP_TROLL_LEATHER: string;
	ARMOUR_GLOVE1: string;
	ARMOUR_GLOVE2: string;
	ARMOUR_GLOVE3: string;
	ARMOUR_GLOVE4: string;
	ARMOUR_GLOVE5: string;
	ARMOUR_GOLD_DRAGON_ARMOUR: string;
	ARMOUR_HEADGEAR_CAP_JESTER: string;
	ARMOUR_HEADGEAR_ELVEN_LEATHER_HELM: string;
	ARMOUR_HEADGEAR_HAT1: string;
	ARMOUR_HEADGEAR_HAT2: string;
	ARMOUR_HEADGEAR_HAT3: string;
	ARMOUR_HEADGEAR_HELMET1: string;
	ARMOUR_HEADGEAR_HELMET2: string;
	ARMOUR_HEADGEAR_HELMET3: string;
	ARMOUR_HEADGEAR_HELMET4: string;
	ARMOUR_HEADGEAR_HELMET5: string;
	ARMOUR_HEADGEAR_HELMET_ART1: string;
	ARMOUR_HEADGEAR_HELMET_ART2: string;
	ARMOUR_HEADGEAR_HELMET_ART3: string;
	ARMOUR_HEADGEAR_HELMET_EGO1: string;
	ARMOUR_HEADGEAR_HELMET_EGO2: string;
	ARMOUR_HEADGEAR_HELMET_EGO3: string;
	ARMOUR_HEADGEAR_HELMET_EGO4: string;
	ARMOUR_ICE_DRAGON_ARMOUR: string;
	ARMOUR_IRON_TROLL_LEATHER: string;
	ARMOUR_LEATHER_ARMOUR1: string;
	ARMOUR_LEATHER_ARMOUR2: string;
	ARMOUR_LEATHER_ARMOUR3: string;
	ARMOUR_PEARL_DRAGON_ARMOUR: string;
	ARMOUR_PLATE1: string;
	ARMOUR_PLATE2: string;
	ARMOUR_PLATE3: string;
	ARMOUR_QUICKSILVER_DRAGON_SCALE_MAIL: string;
	ARMOUR_RED_DRAGON_SCALE_MAIL: string;
	ARMOUR_RING_MAIL1: string;
	ARMOUR_RING_MAIL2: string;
	ARMOUR_RING_MAIL3: string;
	ARMOUR_ROBE1: string;
	ARMOUR_ROBE2: string;
	ARMOUR_ROBE_ART1: string;
	ARMOUR_ROBE_ART2: string;
	ARMOUR_ROBE_EGO1: string;
	ARMOUR_ROBE_EGO2: string;
	ARMOUR_SCALE_MAIL1: string;
	ARMOUR_SCALE_MAIL2: string;
	ARMOUR_SCALE_MAIL3: string;
	ARMOUR_SCARF1: string;
	ARMOUR_SCARF2_1: string;
	ARMOUR_SCARF2_2: string;
	ARMOUR_SCARF2_3: string;
	ARMOUR_SCARF3: string;
	ARMOUR_SHADOW_DRAGON_SCALE_MAIL: string;
	ARMOUR_SHIELDS_BUCKLER1: string;
	ARMOUR_SHIELDS_BUCKLER2: string;
	ARMOUR_SHIELDS_BUCKLER3: string;
	ARMOUR_SHIELDS_BUCKLER_SPRIGGAN: string;
	ARMOUR_SHIELDS_LARGE_SHIELD1: string;
	ARMOUR_SHIELDS_LARGE_SHIELD2: string;
	ARMOUR_SHIELDS_LARGE_SHIELD3: string;
	ARMOUR_SHIELDS_LSHIELD_DD_DK: string;
	ARMOUR_SHIELDS_LSHIELD_LOUISE: string;
	ARMOUR_SHIELDS_SHIELD1: string;
	ARMOUR_SHIELDS_SHIELD2: string;
	ARMOUR_SHIELDS_SHIELD3: string;
	ARMOUR_SHIELDS_SHIELD_DD: string;
	ARMOUR_SHIELDS_SHIELD_DD_SCION: string;
	ARMOUR_SHIELDS_SHIELD_DONALD: string;
	ARMOUR_SILVER_DRAGON_SCALE_MAIL: string;
	ARMOUR_SWAMP_DRAGON_ARMOUR: string;
	ARMOUR_TROLL_LEATHER_ARMOUR: string;
	BOOK_ARTEFACT_BOOKMARK: string;
	BOOK_ARTEFACT_BUCKLE: string;
	BOOK_ARTEFACT_THICK: string;
	BOOK_ARTEFACT_THIN: string;
	BOOK_ARTEFACT_VELLUM: string;
	BOOK_ARTEFACT_VELVET: string;
	BOOK_ARTEFACT_WRINKLED: string;
	BOOK_OF_THE_DEAD: string;
	BOOK_BRONZE: string;
	BOOK_CLOTH: string;
	BOOK_COPPER: string;
	BOOK_CYAN: string;
	BOOK_DARK_BLUE: string;
	BOOK_DARK_BROWN: string;
	BOOK_DARK_GRAY: string;
	BOOK_DARK_GREEN: string;
	BOOK_GOLD: string;
	BOOK_LEATHER: string;
	BOOK_LIGHT_BLUE: string;
	BOOK_LIGHT_BROWN: string;
	BOOK_LIGHT_GRAY: string;
	BOOK_LIGHT_GREEN: string;
	BOOK_MAGENTA: string;
	BOOK_MANUAL1: string;
	BOOK_MANUAL2: string;
	BOOK_METAL_BLUE: string;
	BOOK_METAL_CYAN: string;
	BOOK_METAL_GREEN: string;
	BOOK_PARCHMENT: string;
	BOOK_PINK: string;
	BOOK_PLAID: string;
	BOOK_PURPLE: string;
	BOOK_RED: string;
	BOOK_SILVER: string;
	BOOK_TAN: string;
	BOOK_TURQUOISE: string;
	BOOK_WHITE: string;
	BOOK_YELLOW: string;
	FOOD_APPLE: string;
	FOOD_APRICOT: string;
	FOOD_BANANA: string;
	FOOD_BEEF_JERKY: string;
	FOOD_BONE1: string;
	FOOD_BONE2: string;
	FOOD_BONE3: string;
	FOOD_BONE4: string;
	FOOD_BONE_HUMANOID1: string;
	FOOD_BONE_HUMANOID2: string;
	FOOD_BONE_HUMANOID3: string;
	FOOD_BONE_HUMANOID4: string;
	FOOD_BREAD_RATION: string;
	FOOD_CHEESE: string;
	FOOD_CHOKO: string;
	FOOD_CHUNK: string;
	FOOD_CHUNK_BRANDS_DECAY: string;
	FOOD_CHUNK_BRANDS_FORBIDDEN: string;
	FOOD_CHUNK_BRANDS_INEDIBLE: string;
	FOOD_CHUNK_BRANDS_POISON: string;
	FOOD_CHUNK_ROTTEN: string;
	FOOD_FRUIT: string;
	FOOD_GRAPE: string;
	FOOD_HONEYCOMB: string;
	FOOD_LEMON: string;
	FOOD_MEAT_RATION: string;
	FOOD_ORANGE: string;
	FOOD_PEAR: string;
	FOOD_PIZZA: string;
	FOOD_SAUSAGE: string;
	FOOD_SNOZZCUMBER: string;
	FOOD_STRAWBERRY: string;
	GOLD_01: string;
	GOLD_02: string;
	GOLD_03: string;
	GOLD_04: string;
	GOLD_05: string;
	GOLD_06: string;
	GOLD_07: string;
	GOLD_08: string;
	GOLD_09: string;
	GOLD_10: string;
	GOLD_16: string;
	GOLD_19: string;
	GOLD_23: string;
	GOLD_25: string;
	MISC_BOTTLE: string;
	MISC_BOX: string;
	MISC_CRYSTAL: string;
	MISC_FAN: string;
	MISC_FAN_INERT: string;
	MISC_HORN: string;
	MISC_LAMP: string;
	MISC_LAMP_INERT: string;
	MISC_LANTERN: string;
	MISC_LIGHTNING_ROD: string;
	MISC_LIGHTNING_INERT: string;
	MISC_ORB: string;
	MISC_ORB2: string;
	MISC_PHANTOM_MIRROR: string;
	MISC_PHIAL: string;
	MISC_PHIAL_INERT: string;
	MISC_QUAD: string;
	MISC_SACK: string;
	MISC_STONE: string;
	MISC_STONE_INERT: string;
	MISC_ZIGFIG: string;
	MISC_GENERIC: string;
	MISC_RUNE_ABYSS: string;
	MISC_RUNE_CEREBOV: string;
	MISC_RUNE_COCYTUS: string;
	MISC_RUNE_DEMONIC_1: string;
	MISC_RUNE_DEMONIC_2: string;
	MISC_RUNE_DEMONIC_3: string;
	MISC_RUNE_DEMONIC_4: string;
	MISC_RUNE_DEMONIC_5: string;
	MISC_RUNE_DEMONIC_6: string;
	MISC_RUNE_DIS: string;
	MISC_RUNE_ELVEN: string;
	MISC_RUNE_GEHENNA: string;
	MISC_RUNE_GLOORX_VLOQ: string;
	MISC_RUNE_LOM_LOBON: string;
	MISC_RUNE_MNOLEG: string;
	MISC_RUNE_SHOALS: string;
	MISC_RUNE_SLIME: string;
	MISC_RUNE_SNAKE: string;
	MISC_RUNE_SPIDER: string;
	MISC_RUNE_SWAMP: string;
	MISC_RUNE_TARTARUS: string;
	MISC_RUNE_TOMB: string;
	MISC_RUNE_VAULTS: string;
	MISC_UNCOLLECTED_ORB: string;
	MISC_UNCOLLECTED_GENERIC: string;
	MISC_UNCOLLECTED_RUNE_ABYSS: string;
	MISC_UNCOLLECTED_RUNE_CEREBOV: string;
	MISC_UNCOLLECTED_RUNE_COCYTUS: string;
	MISC_UNCOLLECTED_RUNE_DEMONIC: string;
	MISC_UNCOLLECTED_RUNE_DIS: string;
	MISC_UNCOLLECTED_RUNE_ELVEN: string;
	MISC_UNCOLLECTED_RUNE_GEHENNA: string;
	MISC_UNCOLLECTED_RUNE_GLOORX_VLOQ: string;
	MISC_UNCOLLECTED_RUNE_LOM_LOBON: string;
	MISC_UNCOLLECTED_RUNE_MNOLEG: string;
	MISC_UNCOLLECTED_RUNE_SHOALS: string;
	MISC_UNCOLLECTED_RUNE_SLIME: string;
	MISC_UNCOLLECTED_RUNE_SNAKE: string;
	MISC_UNCOLLECTED_RUNE_SPIDER: string;
	MISC_UNCOLLECTED_RUNE_SWAMP: string;
	MISC_UNCOLLECTED_RUNE_TARTARUS: string;
	MISC_UNCOLLECTED_RUNE_TOMB: string;
	MISC_UNCOLLECTED_RUNE_VAULTS: string;
	POTION_BLACK: string;
	POTION_BRILLIANT_BLUE: string;
	POTION_BROWN: string;
	POTION_BUBBLY: string;
	POTION_CLOUDY: string;
	POTION_CYAN: string;
	POTION_DARK: string;
	POTION_EFFERVESCENT: string;
	POTION_EMERALD: string;
	POTION_FIZZY: string;
	POTION_GOLDEN: string;
	POTION_AGILITY: string;
	POTION_AMBROSIA: string;
	POTION_BERSERK_RAGE: string;
	POTION_BLOOD: string;
	POTION_BRILLIANCE: string;
	POTION_CANCEL: string;
	POTION_COAGULATED_BLOOD: string;
	POTION_CONFUSION: string;
	POTION_CURE_MUTATION: string;
	POTION_CURING: string;
	POTION_DECAY: string;
	POTION_DEGENERATION: string;
	POTION_EXPERIENCE: string;
	POTION_FLIGHT: string;
	POTION_GAIN_DEXTERITY: string;
	POTION_GAIN_INTELLIGENCE: string;
	POTION_GAIN_STRENGTH: string;
	POTION_GOOD_MUTATION: string;
	POTION_HASTE: string;
	POTION_HEAL_WOUNDS: string;
	POTION_INVISIBILITY: string;
	POTION_LABEL: string;
	POTION_LIGNIFY: string;
	POTION_MAGIC: string;
	POTION_MIGHT: string;
	POTION_MUTATION: string;
	POTION_PARALYSIS: string;
	POTION_POISON: string;
	POTION_PORRIDGE: string;
	POTION_RESISTANCE: string;
	POTION_RESTORE_ABILITIES: string;
	POTION_SLOWING: string;
	POTION_STRONG_POISON: string;
	POTION_MAGENTA: string;
	POTION_MURKY: string;
	POTION_ORANGE: string;
	POTION_PINK: string;
	POTION_PUCE: string;
	POTION_PURPLE_RED: string;
	POTION_RUBY: string;
	POTION_SILVER: string;
	POTION_SKY_BLUE: string;
	POTION_UNKNOWN: string;
	POTION_WHITE: string;
	POTION_YELLOW: string;
	RING_AGATE: string;
	RING_ARTEFACT_MAGE: string;
	RING_ARTEFACT_OCTORING: string;
	RING_ARTEFACT_PHASING: string;
	RING_ARTEFACT_ROBUSTNESS: string;
	RING_ARTEFACT_SHADOWS: string;
	RING_BRASS: string;
	RING_BRONZE: string;
	RING_CLAY: string;
	RING_COPPER: string;
	RING_CORAL: string;
	RING_DIAMOND: string;
	RING_EMERALD: string;
	RING_GLASS: string;
	RING_GOLD: string;
	RING_GOLD_BLUE: string;
	RING_GOLD_GREEN: string;
	RING_GOLD_RED: string;
	RING_GRANITE: string;
	RING_ATTENTION: string;
	RING_C_TELEPORT: string;
	RING_DEX: string;
	RING_EVASION: string;
	RING_FIRE: string;
	RING_FLIGHT: string;
	RING_ICE: string;
	RING_INT: string;
	RING_LIFE_PROTECTION: string;
	RING_MAGICAL_POWER: string;
	RING_PROTECTION: string;
	RING_R_COLD: string;
	RING_R_CORROSION: string;
	RING_R_FIRE: string;
	RING_R_MAGIC: string;
	RING_R_POISON: string;
	RING_S_ATTR: string;
	RING_SEE_INVIS: string;
	RING_SLAYING: string;
	RING_STEALTH: string;
	RING_STR: string;
	RING_TELEPORT: string;
	RING_WIZARDRY: string;
	RING_IRON: string;
	RING_IVORY: string;
	RING_JADE: string;
	RING_MOONSTONE: string;
	RING_OPAL: string;
	RING_PEARL: string;
	RING_PLAIN_BLACK: string;
	RING_PLAIN_RED: string;
	RING_PLAIN_YELLOW: string;
	RING_RANDARTS_ANVIL: string;
	RING_RANDARTS_BLOOD: string;
	RING_RANDARTS_BRONZE_FLOWER: string;
	RING_RANDARTS_DARK: string;
	RING_RANDARTS_DOUBLE: string;
	RING_RANDARTS_EYE: string;
	RING_RANDARTS_FIRE: string;
	RING_RANDARTS_FLOWER: string;
	RING_RANDARTS_FOUR_COLOUR: string;
	RING_RANDARTS_GREEN: string;
	RING_RANDARTS_ICE: string;
	RING_RANDARTS_PINK: string;
	RING_RANDARTS_RED_BLUE: string;
	RING_RANDARTS_SNAKE: string;
	RING_RANDARTS_ZIRCON: string;
	RING_RUBY: string;
	RING_SILVER: string;
	RING_STEEL: string;
	RING_TIGER_EYE: string;
	RING_TOURMALINE: string;
	RING_WOODEN: string;
	ROD00: string;
	ROD01: string;
	ROD02: string;
	ROD03: string;
	ROD04: string;
	ROD05: string;
	ROD06: string;
	ROD07: string;
	ROD08: string;
	ROD09: string;
	SCROLL_ACQUIREMENT: string;
	SCROLL_AMNESIA: string;
	SCROLL_BLINKING: string;
	SCROLL_BRAND_WEAPON: string;
	SCROLL_CURSE_JEWELLERY: string;
	SCROLL_CURSE_ARMOUR: string;
	SCROLL_CURSE_WEAPON: string;
	SCROLL_ENCHANT_WEAPON: string;
	SCROLL_ENCHANT_ARMOUR: string;
	SCROLL_FEAR: string;
	SCROLL_FOG: string;
	SCROLL_HOLY_WORD: string;
	SCROLL_IDENTIFY: string;
	SCROLL_IMMOLATION: string;
	SCROLL_MAGIC_MAPPING: string;
	SCROLL_NOISE: string;
	SCROLL_RANDOM_USELESSNESS: string;
	SCROLL_RECHARGING: string;
	SCROLL_REMOVE_CURSE: string;
	SCROLL_SILENCE: string;
	SCROLL_TELEPORTATION: string;
	SCROLL_TORMENT: string;
	SCROLL_UNHOLY_CREATION: string;
	SCROLL_VULNERABILITY: string;
	SCROLL_BLUE: string;
	SCROLL_BROWN: string;
	SCROLL_CYAN: string;
	SCROLL_GREEN: string;
	SCROLL_GREY: string;
	SCROLL_PURPLE: string;
	SCROLL_RED: string;
	SCROLL_YELLOW: string;
	SCROLL_SCROLL: string;
	STAFF_AIR: string;
	STAFF_CHANNELING: string;
	STAFF_COLD: string;
	STAFF_CONJURATION: string;
	STAFF_DEATH: string;
	STAFF_EARTH: string;
	STAFF_ENCHANTMENT: string;
	STAFF_ENERGY: string;
	STAFF_FIRE: string;
	STAFF_POISON: string;
	STAFF_POWER: string;
	STAFF_SUMMONING: string;
	STAFF_WIZARDRY: string;
	STAFF_STAFF00: string;
	STAFF_STAFF01: string;
	STAFF_STAFF02: string;
	STAFF_STAFF03: string;
	STAFF_STAFF04: string;
	STAFF_STAFF05: string;
	STAFF_STAFF06: string;
	STAFF_STAFF07: string;
	STAFF_STAFF08: string;
	STAFF_STAFF09: string;
	WAND_GEM_BONE: string;
	WAND_GEM_BRASS: string;
	WAND_GEM_BRONZE: string;
	WAND_GEM_COPPER: string;
	WAND_GEM_GLASS: string;
	WAND_GEM_GOLD: string;
	WAND_GEM_IRON: string;
	WAND_GEM_IVORY: string;
	WAND_GEM_LEAD: string;
	WAND_GEM_PLASTIC: string;
	WAND_GEM_SILVER: string;
	WAND_GEM_WOOD: string;
	WAND_ACID: string;
	WAND_CLOUDS: string;
	WAND_CONFUSION: string;
	WAND_DIGGING: string;
	WAND_DISINTEGRATION: string;
	WAND_ENSLAVEMENT: string;
	WAND_FLAME: string;
	WAND_HASTING: string;
	WAND_HEAL_WOUNDS: string;
	WAND_ICEBLAST: string;
	WAND_LIGHTNING: string;
	WAND_PARALYSIS: string;
	WAND_POLYMORPH: string;
	WAND_RANDOM_EFFECTS: string;
	WAND_SCATTERSHOT: string;
	WAND_SLOWING: string;
	WAND_TELEPORTATION: string;
	WEAPON_ARTEFACT_DEMON_AXE: string;
	WEAPON_ARTEFACT_GLAIVE_OF_PRUNE: string;
	WEAPON_ARTEFACT_MACE_OF_VARIABILITY: string;
	WEAPON_ARTEFACT_MAJIN: string;
	WEAPON_ARTEFACT_SCEPTRE_OF_ASMODEUS: string;
	WEAPON_ARTEFACT_SCEPTRE_OF_TORMENT: string;
	WEAPON_ARTEFACT_SCYTHE_OF_CURSES: string;
	WEAPON_ARTEFACT_SINGING_SWORD: string;
	WEAPON_ARTEFACT_STAFF_OF_DISPATER: string;
	WEAPON_ARTEFACT_STAFF_OF_OLGREB: string;
	WEAPON_ARTEFACT_SWORD_OF_CEREBOV: string;
	WEAPON_ARTEFACT_SWORD_OF_POWER: string;
	WEAPON_ARTEFACT_SWORD_OF_ZONGULDROK: string;
	WEAPON_ARTEFACT_VAMPIRES_TOOTH: string;
	WEAPON_ARTEFACT_WRATH_OF_TROG: string;
	WEAPON_ARTEFACT_WUCAD_MU: string;
	WEAPON_ARTEFACT_ZEALOT_SWORD: string;
	WEAPON_ARTEFACT_ARC_BLADE: string;
	WEAPON_ARTEFACT_ARGA: string;
	WEAPON_ARTEFACT_AXE_OF_WOE: string;
	WEAPON_ARTEFACT_BLOODBANE: string;
	WEAPON_ARTEFACT_BLOWGUN: string;
	WEAPON_ARTEFACT_BOTONO: string;
	WEAPON_ARTEFACT_BRILLIANCE: string;
	WEAPON_ARTEFACT_CHILLY_DEATH: string;
	WEAPON_ARTEFACT_CRYSTAL_SPEAR: string;
	WEAPON_ARTEFACT_CUTLASS: string;
	WEAPON_ARTEFACT_DAMNATION: string;
	WEAPON_ARTEFACT_DARK_MAUL: string;
	WEAPON_ARTEFACT_DOOM_KNIGHT: string;
	WEAPON_ARTEFACT_ELEMENTAL: string;
	WEAPON_ARTEFACT_EOS: string;
	WEAPON_ARTEFACT_FINISHER: string;
	WEAPON_ARTEFACT_FIRESTARTER: string;
	WEAPON_ARTEFACT_FLAMING_DEATH: string;
	WEAPON_ARTEFACT_FROSTBITE: string;
	WEAPON_ARTEFACT_GUARD: string;
	WEAPON_ARTEFACT_GYRE: string;
	WEAPON_ARTEFACT_KATANA: string;
	WEAPON_ARTEFACT_KNIFE_OF_ACCURACY: string;
	WEAPON_ARTEFACT_LEECH: string;
	WEAPON_ARTEFACT_MORG: string;
	WEAPON_ARTEFACT_OCTOPUS_KING: string;
	WEAPON_ARTEFACT_ORDER: string;
	WEAPON_ARTEFACT_PIERCER: string;
	WEAPON_ARTEFACT_PLUTONIUM: string;
	WEAPON_ARTEFACT_PUNK: string;
	WEAPON_ARTEFACT_RIFT: string;
	WEAPON_ARTEFACT_SHILLELAGH: string;
	WEAPON_ARTEFACT_SKULLCRUSHER: string;
	WEAPON_ARTEFACT_SNAKEBITE: string;
	WEAPON_ARTEFACT_SNIPER: string;
	WEAPON_ARTEFACT_SPELLBINDER: string;
	WEAPON_ARTEFACT_SPRIGGANS_KNIFE: string;
	WEAPON_ARTEFACT_STORM_BOW: string;
	WEAPON_ARTEFACT_THERMIC_ENGINE: string;
	WEAPON_ARTEFACT_UNDEADHUNTER: string;
	WEAPON_ARTEFACT_WYRMBANE: string;
	WEAPON_ARTEFACT_WYRMBANE1: string;
	WEAPON_ARTEFACT_WYRMBANE2: string;
	WEAPON_ARTEFACT_WYRMBANE3: string;
	WEAPON_ARTEFACT_WYRMBANE4: string;
	WEAPON_ARTEFACT_ZEPHYR: string;
	WEAPON_BARDICHE1: string;
	WEAPON_BARDICHE2: string;
	WEAPON_BARDICHE3: string;
	WEAPON_BATTLE_AXE1: string;
	WEAPON_BATTLE_AXE2: string;
	WEAPON_BATTLE_AXE3: string;
	WEAPON_BLESSED_BLADE: string;
	WEAPON_BRANDS_ANTIMAGIC: string;
	WEAPON_BRANDS_CHAOS: string;
	WEAPON_BRANDS_CONFUSION: string;
	WEAPON_BRANDS_CURARE: string;
	WEAPON_BRANDS_DISPERSAL: string;
	WEAPON_BRANDS_DISTORTION: string;
	WEAPON_BRANDS_DRAINING: string;
	WEAPON_BRANDS_ELECTROCUTION: string;
	WEAPON_BRANDS_EVASION: string;
	WEAPON_BRANDS_EXPLOSION: string;
	WEAPON_BRANDS_FLAMING: string;
	WEAPON_BRANDS_FREEZING: string;
	WEAPON_BRANDS_FRENZY: string;
	WEAPON_BRANDS_HOLY_WRATH: string;
	WEAPON_BRANDS_PAIN: string;
	WEAPON_BRANDS_PARALYSIS: string;
	WEAPON_BRANDS_PENETRATION: string;
	WEAPON_BRANDS_PROTECTION: string;
	WEAPON_BRANDS_REAPING: string;
	WEAPON_BRANDS_RETURNING: string;
	WEAPON_BRANDS_SICKNESS: string;
	WEAPON_BRANDS_SLEEP: string;
	WEAPON_BRANDS_SLOWING: string;
	WEAPON_BRANDS_SPEED: string;
	WEAPON_BRANDS_VAMPIRISM: string;
	WEAPON_BRANDS_VENOM: string;
	WEAPON_BRANDS_VORPAL: string;
	WEAPON_BROAD_AXE1: string;
	WEAPON_BROAD_AXE2: string;
	WEAPON_BROAD_AXE3: string;
	WEAPON_BULLWHIP: string;
	WEAPON_BULLWHIP2: string;
	WEAPON_BULLWHIP3: string;
	WEAPON_CLUB: string;
	WEAPON_CLUB2: string;
	WEAPON_DAGGER: string;
	WEAPON_DAGGER2: string;
	WEAPON_DAGGER3: string;
	WEAPON_DEMON_BLADE: string;
	WEAPON_DEMON_BLADE2: string;
	WEAPON_DEMON_BLADE3: string;
	WEAPON_DEMON_TRIDENT: string;
	WEAPON_DEMON_TRIDENT2: string;
	WEAPON_DEMON_TRIDENT3: string;
	WEAPON_DEMON_WHIP: string;
	WEAPON_DEMON_WHIP2: string;
	WEAPON_DEMON_WHIP3: string;
	WEAPON_DIRE_FLAIL1: string;
	WEAPON_DIRE_FLAIL2: string;
	WEAPON_DIRE_FLAIL3: string;
	WEAPON_DOUBLE_SWORD: string;
	WEAPON_DOUBLE_SWORD2: string;
	WEAPON_DOUBLE_SWORD3: string;
	WEAPON_EVENINGSTAR1: string;
	WEAPON_EVENINGSTAR2: string;
	WEAPON_EVENINGSTAR3: string;
	WEAPON_EXECUTIONER_AXE1: string;
	WEAPON_EXECUTIONER_AXE2: string;
	WEAPON_EXECUTIONER_AXE3: string;
	WEAPON_FALCHION1: string;
	WEAPON_FALCHION2: string;
	WEAPON_FALCHION3: string;
	WEAPON_FLAIL1: string;
	WEAPON_FLAIL2: string;
	WEAPON_FLAIL3: string;
	WEAPON_GIANT_CLUB: string;
	WEAPON_GIANT_CLUB2: string;
	WEAPON_GIANT_CLUB3: string;
	WEAPON_GIANT_SPIKED_CLUB: string;
	WEAPON_GIANT_SPIKED_CLUB2: string;
	WEAPON_GIANT_SPIKED_CLUB3: string;
	WEAPON_GLAIVE1: string;
	WEAPON_GLAIVE2: string;
	WEAPON_GLAIVE3: string;
	WEAPON_GREATSWORD1: string;
	WEAPON_GREATSWORD2: string;
	WEAPON_GREATSWORD3: string;
	WEAPON_HALBERD1: string;
	WEAPON_HALBERD2: string;
	WEAPON_HALBERD3: string;
	WEAPON_HAND_AXE1: string;
	WEAPON_HAND_AXE2: string;
	WEAPON_HAND_AXE3: string;
	WEAPON_LAJATANG1: string;
	WEAPON_LAJATANG2: string;
	WEAPON_LAJATANG3: string;
	WEAPON_LONG_SWORD1: string;
	WEAPON_LONG_SWORD2: string;
	WEAPON_LONG_SWORD3: string;
	WEAPON_MACE1: string;
	WEAPON_MACE2: string;
	WEAPON_MACE3: string;
	WEAPON_MACE_LARGE1: string;
	WEAPON_MACE_LARGE2: string;
	WEAPON_MACE_LARGE3: string;
	WEAPON_MORNINGSTAR1: string;
	WEAPON_MORNINGSTAR2: string;
	WEAPON_MORNINGSTAR3: string;
	WEAPON_QUARTERSTAFF: string;
	WEAPON_QUARTERSTAFF2: string;
	WEAPON_QUARTERSTAFF3: string;
	WEAPON_QUICKBLADE1: string;
	WEAPON_QUICKBLADE2: string;
	WEAPON_QUICKBLADE3: string;
	WEAPON_ARBALEST1: string;
	WEAPON_ARBALEST2: string;
	WEAPON_ARBALEST3: string;
	WEAPON_ARROW1: string;
	WEAPON_ARROW2: string;
	WEAPON_BLOWGUN1: string;
	WEAPON_BLOWGUN2: string;
	WEAPON_CROSSBOW_BOLT1: string;
	WEAPON_CROSSBOW_BOLT2: string;
	WEAPON_FUSTIBALUS1: string;
	WEAPON_FUSTIBALUS2: string;
	WEAPON_FUSTIBALUS3: string;
	WEAPON_HAND_CROSSBOW: string;
	WEAPON_HAND_CROSSBOW2: string;
	WEAPON_HAND_CROSSBOW3: string;
	WEAPON_JAVELIN1: string;
	WEAPON_JAVELIN2: string;
	WEAPON_LONGBOW1: string;
	WEAPON_LONGBOW2: string;
	WEAPON_LONGBOW3: string;
	WEAPON_NEEDLE_C: string;
	WEAPON_NEEDLE_P: string;
	WEAPON_NEEDLE1: string;
	WEAPON_NEEDLE2: string;
	WEAPON_ROCK: string;
	WEAPON_SHORTBOW1: string;
	WEAPON_SHORTBOW2: string;
	WEAPON_SHORTBOW3: string;
	WEAPON_SILVER_ARROW1: string;
	WEAPON_SILVER_ARROW2: string;
	WEAPON_SILVER_CROSSBOW_BOLT1: string;
	WEAPON_SILVER_CROSSBOW_BOLT2: string;
	WEAPON_SILVER_JAVELIN1: string;
	WEAPON_SILVER_JAVELIN2: string;
	WEAPON_SILVER_SLING_BULLET1: string;
	WEAPON_SILVER_SLING_BULLET2: string;
	WEAPON_SILVER_TOMAHAWK: string;
	WEAPON_SLING1: string;
	WEAPON_SLING2: string;
	WEAPON_SLING3: string;
	WEAPON_SLING_BULLET1: string;
	WEAPON_SLING_BULLET2: string;
	WEAPON_STEEL_ARROW1: string;
	WEAPON_STEEL_ARROW2: string;
	WEAPON_STEEL_CROSSBOW_BOLT1: string;
	WEAPON_STEEL_CROSSBOW_BOLT2: string;
	WEAPON_STEEL_JAVELIN1: string;
	WEAPON_STEEL_JAVELIN2: string;
	WEAPON_STEEL_SLING_BULLET1: string;
	WEAPON_STEEL_SLING_BULLET2: string;
	WEAPON_STEEL_TOMAHAWK: string;
	WEAPON_STONE: string;
	WEAPON_THROWING_NET: string;
	WEAPON_TOMAHAWK1: string;
	WEAPON_TOMAHAWK2: string;
	WEAPON_TRIPLE_CROSSBOW: string;
	WEAPON_TRIPLE_CROSSBOW2: string;
	WEAPON_RAPIER1: string;
	WEAPON_RAPIER2: string;
	WEAPON_RAPIER3: string;
	WEAPON_SACRED_SCOURGE: string;
	WEAPON_SCIMITAR1: string;
	WEAPON_SCIMITAR2: string;
	WEAPON_SCIMITAR3: string;
	WEAPON_SCYTHE1: string;
	WEAPON_SCYTHE2: string;
	WEAPON_SCYTHE3: string;
	WEAPON_SHORT_SWORD1: string;
	WEAPON_SHORT_SWORD2: string;
	WEAPON_SHORT_SWORD3: string;
	WEAPON_SPEAR1: string;
	WEAPON_SPEAR2: string;
	WEAPON_SPEAR3: string;
	WEAPON_STAFF: string;
	WEAPON_STAFF_MUMMY: string;
	WEAPON_TRIDENT1: string;
	WEAPON_TRIDENT2: string;
	WEAPON_TRIDENT3: string;
	WEAPON_TRIPLE_SWORD: string;
	WEAPON_TRIPLE_SWORD2: string;
	WEAPON_TRIPLE_SWORD3: string;
	WEAPON_TRISHULA: string;
	WEAPON_WAR_AXE1: string;
	WEAPON_WAR_AXE2: string;
	WEAPON_WAR_AXE3: string;
}

export const itemTiles: IitemTiles = {
	AMULET_AMETHYST: "item/amulet/amethyst.png",
	AMULET_ARTEFACT_AIR: "item/amulet/artefact/urand_air.png",
	AMULET_ARTEFACT_BLOODLUST: "item/amulet/artefact/urand_bloodlust.png",
	AMULET_ARTEFACT_BROOCH_OF_SHIELDING: "item/amulet/artefact/urand_brooch_of_shielding.png",
	AMULET_ARTEFACT_CEKUGOB: "item/amulet/artefact/urand_cekugob.png",
	AMULET_ARTEFACT_FINGER: "item/amulet/artefact/urand_finger.png",
	AMULET_ARTEFACT_FOUR_WINDS: "item/amulet/artefact/urand_four_winds.png",
	AMULET_ARTEFACT_VITALITY: "item/amulet/artefact/urand_vitality.png",
	AMULET_BERYL: "item/amulet/beryl.png",
	AMULET_BLUE: "item/amulet/blue.png",
	AMULET_BONE: "item/amulet/bone.png",
	AMULET_BRASS: "item/amulet/brass.png",
	AMULET_BRONZE: "item/amulet/bronze.png",
	AMULET_CABOCHON: "item/amulet/cabochon.png",
	AMULET_CAMEO: "item/amulet/cameo.png",
	AMULET_CITRINE: "item/amulet/citrine.png",
	AMULET_COPPER: "item/amulet/copper.png",
	AMULET_DIAMOND: "item/amulet/diamond.png",
	AMULET_EMERALD: "item/amulet/emerald.png",
	AMULET_FILIGREE: "item/amulet/filigree.png",
	AMULET_FLOURESCENT: "item/amulet/flourescent.png",
	AMULET_GARNET: "item/amulet/garnet.png",
	AMULET_GOLDEN: "item/amulet/golden.png",
	AMULET_ACROBAT: "item/amulet/i-acrobat.png",
	AMULET_FAITH: "item/amulet/i-faith.png",
	AMULET_GOURMAND: "item/amulet/i-gourmand.png",
	AMULET_HARM: "item/amulet/i-harm.png",
	AMULET_INACCURACY: "item/amulet/i-inaccuracy.png",
	AMULET_M_REGENERATION: "item/amulet/i-m-regeneration.png",
	AMULET_RAGE: "item/amulet/i-rage.png",
	AMULET_REFLECTION: "item/amulet/i-reflection.png",
	AMULET_REGENERATION: "item/amulet/i-regeneration.png",
	AMULET_SPIRIT: "item/amulet/i-spirit.png",
	AMULET_JADE: "item/amulet/jade.png",
	AMULET_JASPER: "item/amulet/jasper.png",
	AMULET_LAPIS_LAZULI: "item/amulet/lapis_lazuli.png",
	AMULET_MALACHITE: "item/amulet/malachite.png",
	AMULET_PEARL: "item/amulet/pearl.png",
	AMULET_PERIDOT: "item/amulet/peridot.png",
	AMULET_PLATINUM: "item/amulet/platinum.png",
	AMULET_RANDARTS_AZURE: "item/amulet/randarts/azure.png",
	AMULET_RANDARTS_CLUSTER: "item/amulet/randarts/cluster.png",
	AMULET_RANDARTS_DROP: "item/amulet/randarts/drop.png",
	AMULET_RANDARTS_KNOT: "item/amulet/randarts/knot.png",
	AMULET_RANDARTS_SCARAB: "item/amulet/randarts/scarab.png",
	AMULET_RANDARTS_SKULL: "item/amulet/randarts/skull.png",
	AMULET_RANDARTS_SPIDER: "item/amulet/randarts/spider.png",
	AMULET_RANDARTS_SUN: "item/amulet/randarts/sun.png",
	AMULET_RUBY: "item/amulet/ruby.png",
	AMULET_SAPPHIRE: "item/amulet/sapphire.png",
	AMULET_SILVER: "item/amulet/silver.png",
	AMULET_SOAPSTONE: "item/amulet/soapstone.png",
	AMULET_STEEL: "item/amulet/steel.png",
	AMULET_ZIRCONIUM: "item/amulet/zirconium.png",
	ARMOUR_ACID_DRAGON_ARMOUR: "item/armour/acid_dragon_armour.png",
	ARMOUR_ANIMAL_SKIN1: "item/armour/animal_skin1.png",
	ARMOUR_ANIMAL_SKIN2: "item/armour/animal_skin2.png",
	ARMOUR_ANIMAL_SKIN3: "item/armour/animal_skin3.png",
	ARMOUR_ARTEFACT_ALCHEMIST: "item/armour/artefact/urand_alchemist.png",
	ARMOUR_ARTEFACT_ASSASSIN: "item/armour/artefact/urand_assassin.png",
	ARMOUR_ARTEFACT_AUGMENTATION: "item/armour/artefact/urand_augmentation.png",
	ARMOUR_ARTEFACT_BEAR: "item/armour/artefact/urand_bear.png",
	ARMOUR_ARTEFACT_BK_BARDING: "item/armour/artefact/urand_bk_barding.png",
	ARMOUR_ARTEFACT_BULLSEYE: "item/armour/artefact/urand_bullseye.png",
	ARMOUR_ARTEFACT_CLOUDS: "item/armour/artefact/urand_clouds.png",
	ARMOUR_ARTEFACT_DRAGONMASK: "item/armour/artefact/urand_dragonmask.png",
	ARMOUR_ARTEFACT_DRAGONSKIN: "item/armour/artefact/urand_dragonskin.png",
	ARMOUR_ARTEFACT_DRAGON_KING: "item/armour/artefact/urand_dragon_king.png",
	ARMOUR_ARTEFACT_DYROVEPREVA: "item/armour/artefact/urand_dyrovepreva.png",
	ARMOUR_ARTEFACT_ETERNAL_TORMENT: "item/armour/artefact/urand_eternal_torment.png",
	ARMOUR_ARTEFACT_ETHERIC_CAGE: "item/armour/artefact/urand_etheric_cage.png",
	ARMOUR_ARTEFACT_FAERIE: "item/armour/artefact/urand_faerie.png",
	ARMOUR_ARTEFACT_FENCER: "item/armour/artefact/urand_fencer.png",
	ARMOUR_ARTEFACT_FLASH: "item/armour/artefact/urand_flash.png",
	ARMOUR_ARTEFACT_FOLLY: "item/armour/artefact/urand_folly.png",
	ARMOUR_ARTEFACT_GONG: "item/armour/artefact/urand_gong.png",
	ARMOUR_ARTEFACT_HIGH_COUNCIL: "item/armour/artefact/urand_high_council.png",
	ARMOUR_ARTEFACT_IGNORANCE: "item/armour/artefact/urand_ignorance.png",
	ARMOUR_ARTEFACT_KRYIAS: "item/armour/artefact/urand_kryias.png",
	ARMOUR_ARTEFACT_LEAR: "item/armour/artefact/urand_lear.png",
	ARMOUR_ARTEFACT_LIGHTNING_SCALES: "item/armour/artefact/urand_lightning_scales.png",
	ARMOUR_ARTEFACT_MAXWELL: "item/armour/artefact/urand_maxwell.png",
	ARMOUR_ARTEFACT_MISFORTUNE: "item/armour/artefact/urand_misfortune.png",
	ARMOUR_ARTEFACT_MOON_TROLL_LEATHER_ARMOUR: "item/armour/artefact/urand_moon_troll_leather_armour.png",
	ARMOUR_ARTEFACT_NIGHT: "item/armour/artefact/urand_night.png",
	ARMOUR_ARTEFACT_ORANGE_CRYSTAL: "item/armour/artefact/urand_orange_crystal.png",
	ARMOUR_ARTEFACT_PONDERING: "item/armour/artefact/urand_pondering.png",
	ARMOUR_ARTEFACT_RATSKIN_CLOAK: "item/armour/artefact/urand_ratskin_cloak.png",
	ARMOUR_ARTEFACT_RESISTANCE: "item/armour/artefact/urand_resistance.png",
	ARMOUR_ARTEFACT_SALAMANDER: "item/armour/artefact/urand_salamander.png",
	ARMOUR_ARTEFACT_SPIDER: "item/armour/artefact/urand_spider.png",
	ARMOUR_ARTEFACT_STARLIGHT: "item/armour/artefact/urand_starlight.png",
	ARMOUR_ARTEFACT_TALOS: "item/armour/artefact/urand_talos.png",
	ARMOUR_ARTEFACT_THIEF: "item/armour/artefact/urand_thief.png",
	ARMOUR_ARTEFACT_VINES: "item/armour/artefact/urand_vines.png",
	ARMOUR_ARTEFACT_WAR: "item/armour/artefact/urand_war.png",
	ARMOUR_ARTEFACT_WARLOCK: "item/armour/artefact/urand_warlock.png",
	ARMOUR_ARTEFACT_ZHOR: "item/armour/artefact/urand_zhor.png",
	ARMOUR_BARDINGS_CENTAUR_BLUE: "item/armour/bardings/centaur_barding_blue.png",
	ARMOUR_BARDINGS_CENTAUR_MAGENTA: "item/armour/bardings/centaur_barding_magenta.png",
	ARMOUR_BARDINGS_CENTAUR_METAL: "item/armour/bardings/centaur_barding_metal.png",
	ARMOUR_BARDINGS_CENTAUR_RED: "item/armour/bardings/centaur_barding_red.png",
	ARMOUR_BARDINGS_NAGA_BLUE: "item/armour/bardings/naga_barding_blue.png",
	ARMOUR_BARDINGS_NAGA_MAGENTA: "item/armour/bardings/naga_barding_magenta.png",
	ARMOUR_BARDINGS_NAGA_METAL: "item/armour/bardings/naga_barding_metal.png",
	ARMOUR_BARDINGS_NAGA_RED: "item/armour/bardings/naga_barding_red.png",
	ARMOUR_BLUE_DRAGON_SCALE_MAIL: "item/armour/blue_dragon_scale_mail.png",
	ARMOUR_BOOTS1_BROWN: "item/armour/boots1_brown.png",
	ARMOUR_BOOTS2_JACKBOOTS: "item/armour/boots2_jackboots.png",
	ARMOUR_BOOTS3_STRIPE: "item/armour/boots3_stripe.png",
	ARMOUR_BOOTS4_GREEN: "item/armour/boots4_green.png",
	ARMOUR_BRANDS_ARCHERY: "item/armour/brands/i-archery.png",
	ARMOUR_BRANDS_ARCHMAGI: "item/armour/brands/i-archmagi.png",
	ARMOUR_BRANDS_CLOUD_IMMUNE: "item/armour/brands/i-cloud-immune.png",
	ARMOUR_BRANDS_COLD_RES: "item/armour/brands/i-cold-res.png",
	ARMOUR_BRANDS_DEXTERITY: "item/armour/brands/i-dexterity.png",
	ARMOUR_BRANDS_FIRE_RES: "item/armour/brands/i-fire-res.png",
	ARMOUR_BRANDS_FLYING: "item/armour/brands/i-flying.png",
	ARMOUR_BRANDS_INTELLIGENCE: "item/armour/brands/i-intelligence.png",
	ARMOUR_BRANDS_INVISIBILITY: "item/armour/brands/i-invisibility.png",
	ARMOUR_BRANDS_JUMPING: "item/armour/brands/i-jumping.png",
	ARMOUR_BRANDS_MAGIC_RES: "item/armour/brands/i-magic-res.png",
	ARMOUR_BRANDS_POISON_RES: "item/armour/brands/i-poison-res.png",
	ARMOUR_BRANDS_PONDEROUS: "item/armour/brands/i-ponderous.png",
	ARMOUR_BRANDS_POSITIVE_ENERGY: "item/armour/brands/i-positive-energy.png",
	ARMOUR_BRANDS_PRESERVATION: "item/armour/brands/i-preservation.png",
	ARMOUR_BRANDS_PROTECTION: "item/armour/brands/i-protection.png",
	ARMOUR_BRANDS_REFLECTION: "item/armour/brands/i-reflection.png",
	ARMOUR_BRANDS_REPULSION: "item/armour/brands/i-repulsion.png",
	ARMOUR_BRANDS_RESISTANCE: "item/armour/brands/i-resistance.png",
	ARMOUR_BRANDS_RUNNING: "item/armour/brands/i-running.png",
	ARMOUR_BRANDS_SEE_INVIS: "item/armour/brands/i-see-invis.png",
	ARMOUR_BRANDS_SPIRIT: "item/armour/brands/i-spirit.png",
	ARMOUR_BRANDS_STEALTH: "item/armour/brands/i-stealth.png",
	ARMOUR_BRANDS_STRENGTH: "item/armour/brands/i-strength.png",
	ARMOUR_CHAIN_MAIL1: "item/armour/chain_mail1.png",
	ARMOUR_CHAIN_MAIL2: "item/armour/chain_mail2.png",
	ARMOUR_CHAIN_MAIL3: "item/armour/chain_mail3.png",
	ARMOUR_CLOAK1_LEATHER: "item/armour/cloak1_leather.png",
	ARMOUR_CLOAK2: "item/armour/cloak2.png",
	ARMOUR_CLOAK3: "item/armour/cloak3.png",
	ARMOUR_CLOAK4: "item/armour/cloak4.png",
	ARMOUR_CRYSTAL_PLATE: "item/armour/crystal_plate.png",
	ARMOUR_CRYSTAL_PLATE2: "item/armour/crystal_plate2.png",
	ARMOUR_CRYSTAL_PLATE3: "item/armour/crystal_plate3.png",
	ARMOUR_DEEP_TROLL_LEATHER: "item/armour/deep_troll_leather.png",
	ARMOUR_GLOVE1: "item/armour/glove1.png",
	ARMOUR_GLOVE2: "item/armour/glove2.png",
	ARMOUR_GLOVE3: "item/armour/glove3.png",
	ARMOUR_GLOVE4: "item/armour/glove4.png",
	ARMOUR_GLOVE5: "item/armour/glove5.png",
	ARMOUR_GOLD_DRAGON_ARMOUR: "item/armour/gold_dragon_armour.png",
	ARMOUR_HEADGEAR_CAP_JESTER: "item/armour/headgear/cap_jester.png",
	ARMOUR_HEADGEAR_ELVEN_LEATHER_HELM: "item/armour/headgear/elven_leather_helm.png",
	ARMOUR_HEADGEAR_HAT1: "item/armour/headgear/hat1.png",
	ARMOUR_HEADGEAR_HAT2: "item/armour/headgear/hat2.png",
	ARMOUR_HEADGEAR_HAT3: "item/armour/headgear/hat3.png",
	ARMOUR_HEADGEAR_HELMET1: "item/armour/headgear/helmet1.png",
	ARMOUR_HEADGEAR_HELMET2: "item/armour/headgear/helmet2.png",
	ARMOUR_HEADGEAR_HELMET3: "item/armour/headgear/helmet3.png",
	ARMOUR_HEADGEAR_HELMET4: "item/armour/headgear/helmet4.png",
	ARMOUR_HEADGEAR_HELMET5: "item/armour/headgear/helmet5.png",
	ARMOUR_HEADGEAR_HELMET_ART1: "item/armour/headgear/helmet_art1.png",
	ARMOUR_HEADGEAR_HELMET_ART2: "item/armour/headgear/helmet_art2.png",
	ARMOUR_HEADGEAR_HELMET_ART3: "item/armour/headgear/helmet_art3.png",
	ARMOUR_HEADGEAR_HELMET_EGO1: "item/armour/headgear/helmet_ego1.png",
	ARMOUR_HEADGEAR_HELMET_EGO2: "item/armour/headgear/helmet_ego2.png",
	ARMOUR_HEADGEAR_HELMET_EGO3: "item/armour/headgear/helmet_ego3.png",
	ARMOUR_HEADGEAR_HELMET_EGO4: "item/armour/headgear/helmet_ego4.png",
	ARMOUR_ICE_DRAGON_ARMOUR: "item/armour/ice_dragon_armour.png",
	ARMOUR_IRON_TROLL_LEATHER: "item/armour/iron_troll_leather.png",
	ARMOUR_LEATHER_ARMOUR1: "item/armour/leather_armour1.png",
	ARMOUR_LEATHER_ARMOUR2: "item/armour/leather_armour2.png",
	ARMOUR_LEATHER_ARMOUR3: "item/armour/leather_armour3.png",
	ARMOUR_PEARL_DRAGON_ARMOUR: "item/armour/pearl_dragon_armour.png",
	ARMOUR_PLATE1: "item/armour/plate1.png",
	ARMOUR_PLATE2: "item/armour/plate2.png",
	ARMOUR_PLATE3: "item/armour/plate3.png",
	ARMOUR_QUICKSILVER_DRAGON_SCALE_MAIL: "item/armour/quicksilver_dragon_scale_mail.png",
	ARMOUR_RED_DRAGON_SCALE_MAIL: "item/armour/red_dragon_scale_mail.png",
	ARMOUR_RING_MAIL1: "item/armour/ring_mail1.png",
	ARMOUR_RING_MAIL2: "item/armour/ring_mail2.png",
	ARMOUR_RING_MAIL3: "item/armour/ring_mail3.png",
	ARMOUR_ROBE1: "item/armour/robe1.png",
	ARMOUR_ROBE2: "item/armour/robe2.png",
	ARMOUR_ROBE_ART1: "item/armour/robe_art1.png",
	ARMOUR_ROBE_ART2: "item/armour/robe_art2.png",
	ARMOUR_ROBE_EGO1: "item/armour/robe_ego1.png",
	ARMOUR_ROBE_EGO2: "item/armour/robe_ego2.png",
	ARMOUR_SCALE_MAIL1: "item/armour/scale_mail1.png",
	ARMOUR_SCALE_MAIL2: "item/armour/scale_mail2.png",
	ARMOUR_SCALE_MAIL3: "item/armour/scale_mail3.png",
	ARMOUR_SCARF1: "item/armour/scarf1.png",
	ARMOUR_SCARF2_1: "item/armour/scarf2_1.png",
	ARMOUR_SCARF2_2: "item/armour/scarf2_2.png",
	ARMOUR_SCARF2_3: "item/armour/scarf2_3.png",
	ARMOUR_SCARF3: "item/armour/scarf3.png",
	ARMOUR_SHADOW_DRAGON_SCALE_MAIL: "item/armour/shadow_dragon_scale_mail.png",
	ARMOUR_SHIELDS_BUCKLER1: "item/armour/shields/buckler1.png",
	ARMOUR_SHIELDS_BUCKLER2: "item/armour/shields/buckler2.png",
	ARMOUR_SHIELDS_BUCKLER3: "item/armour/shields/buckler3.png",
	ARMOUR_SHIELDS_BUCKLER_SPRIGGAN: "item/armour/shields/buckler_spriggan.png",
	ARMOUR_SHIELDS_LARGE_SHIELD1: "item/armour/shields/large_shield1.png",
	ARMOUR_SHIELDS_LARGE_SHIELD2: "item/armour/shields/large_shield2.png",
	ARMOUR_SHIELDS_LARGE_SHIELD3: "item/armour/shields/large_shield3.png",
	ARMOUR_SHIELDS_LSHIELD_DD_DK: "item/armour/shields/lshield_dd_dk.png",
	ARMOUR_SHIELDS_LSHIELD_LOUISE: "item/armour/shields/lshield_louise.png",
	ARMOUR_SHIELDS_SHIELD1: "item/armour/shields/shield1.png",
	ARMOUR_SHIELDS_SHIELD2: "item/armour/shields/shield2.png",
	ARMOUR_SHIELDS_SHIELD3: "item/armour/shields/shield3.png",
	ARMOUR_SHIELDS_SHIELD_DD: "item/armour/shields/shield_dd.png",
	ARMOUR_SHIELDS_SHIELD_DD_SCION: "item/armour/shields/shield_dd_scion.png",
	ARMOUR_SHIELDS_SHIELD_DONALD: "item/armour/shields/shield_donald.png",
	ARMOUR_SILVER_DRAGON_SCALE_MAIL: "item/armour/silver_dragon_scale_mail.png",
	ARMOUR_SWAMP_DRAGON_ARMOUR: "item/armour/swamp_dragon_armour.png",
	ARMOUR_TROLL_LEATHER_ARMOUR: "item/armour/troll_leather_armour.png",
	BOOK_ARTEFACT_BOOKMARK: "item/book/artefact/bookmark.png",
	BOOK_ARTEFACT_BUCKLE: "item/book/artefact/buckle.png",
	BOOK_ARTEFACT_THICK: "item/book/artefact/thick.png",
	BOOK_ARTEFACT_THIN: "item/book/artefact/thin.png",
	BOOK_ARTEFACT_VELLUM: "item/book/artefact/vellum.png",
	BOOK_ARTEFACT_VELVET: "item/book/artefact/velvet.png",
	BOOK_ARTEFACT_WRINKLED: "item/book/artefact/wrinkled.png",
	BOOK_OF_THE_DEAD: "item/book/book_of_the_dead.png",
	BOOK_BRONZE: "item/book/bronze.png",
	BOOK_CLOTH: "item/book/cloth.png",
	BOOK_COPPER: "item/book/copper.png",
	BOOK_CYAN: "item/book/cyan.png",
	BOOK_DARK_BLUE: "item/book/dark_blue.png",
	BOOK_DARK_BROWN: "item/book/dark_brown.png",
	BOOK_DARK_GRAY: "item/book/dark_gray.png",
	BOOK_DARK_GREEN: "item/book/dark_green.png",
	BOOK_GOLD: "item/book/gold.png",
	BOOK_LEATHER: "item/book/leather.png",
	BOOK_LIGHT_BLUE: "item/book/light_blue.png",
	BOOK_LIGHT_BROWN: "item/book/light_brown.png",
	BOOK_LIGHT_GRAY: "item/book/light_gray.png",
	BOOK_LIGHT_GREEN: "item/book/light_green.png",
	BOOK_MAGENTA: "item/book/magenta.png",
	BOOK_MANUAL1: "item/book/manual1.png",
	BOOK_MANUAL2: "item/book/manual2.png",
	BOOK_METAL_BLUE: "item/book/metal_blue.png",
	BOOK_METAL_CYAN: "item/book/metal_cyan.png",
	BOOK_METAL_GREEN: "item/book/metal_green.png",
	BOOK_PARCHMENT: "item/book/parchment.png",
	BOOK_PINK: "item/book/pink.png",
	BOOK_PLAID: "item/book/plaid.png",
	BOOK_PURPLE: "item/book/purple.png",
	BOOK_RED: "item/book/red.png",
	BOOK_SILVER: "item/book/silver.png",
	BOOK_TAN: "item/book/tan.png",
	BOOK_TURQUOISE: "item/book/turquoise.png",
	BOOK_WHITE: "item/book/white.png",
	BOOK_YELLOW: "item/book/yellow.png",
	FOOD_APPLE: "item/food/apple.png",
	FOOD_APRICOT: "item/food/apricot.png",
	FOOD_BANANA: "item/food/banana.png",
	FOOD_BEEF_JERKY: "item/food/beef_jerky.png",
	FOOD_BONE1: "item/food/bone1.png",
	FOOD_BONE2: "item/food/bone2.png",
	FOOD_BONE3: "item/food/bone3.png",
	FOOD_BONE4: "item/food/bone4.png",
	FOOD_BONE_HUMANOID1: "item/food/bone_humanoid1.png",
	FOOD_BONE_HUMANOID2: "item/food/bone_humanoid2.png",
	FOOD_BONE_HUMANOID3: "item/food/bone_humanoid3.png",
	FOOD_BONE_HUMANOID4: "item/food/bone_humanoid4.png",
	FOOD_BREAD_RATION: "item/food/bread_ration.png",
	FOOD_CHEESE: "item/food/cheese.png",
	FOOD_CHOKO: "item/food/choko.png",
	FOOD_CHUNK: "item/food/chunk.png",
	FOOD_CHUNK_BRANDS_DECAY: "item/food/chunk_brands/i-decay.png",
	FOOD_CHUNK_BRANDS_FORBIDDEN: "item/food/chunk_brands/i-forbidden.png",
	FOOD_CHUNK_BRANDS_INEDIBLE: "item/food/chunk_brands/i-inedible.png",
	FOOD_CHUNK_BRANDS_POISON: "item/food/chunk_brands/i-poison.png",
	FOOD_CHUNK_ROTTEN: "item/food/chunk_rotten.png",
	FOOD_FRUIT: "item/food/fruit.png",
	FOOD_GRAPE: "item/food/grape.png",
	FOOD_HONEYCOMB: "item/food/honeycomb.png",
	FOOD_LEMON: "item/food/lemon.png",
	FOOD_MEAT_RATION: "item/food/meat_ration.png",
	FOOD_ORANGE: "item/food/orange.png",
	FOOD_PEAR: "item/food/pear.png",
	FOOD_PIZZA: "item/food/pizza.png",
	FOOD_SAUSAGE: "item/food/sausage.png",
	FOOD_SNOZZCUMBER: "item/food/snozzcumber.png",
	FOOD_STRAWBERRY: "item/food/strawberry.png",
	GOLD_01: "item/gold/01.png",
	GOLD_02: "item/gold/02.png",
	GOLD_03: "item/gold/03.png",
	GOLD_04: "item/gold/04.png",
	GOLD_05: "item/gold/05.png",
	GOLD_06: "item/gold/06.png",
	GOLD_07: "item/gold/07.png",
	GOLD_08: "item/gold/08.png",
	GOLD_09: "item/gold/09.png",
	GOLD_10: "item/gold/10.png",
	GOLD_16: "item/gold/16.png",
	GOLD_19: "item/gold/19.png",
	GOLD_23: "item/gold/23.png",
	GOLD_25: "item/gold/25.png",
	MISC_BOTTLE: "item/misc/misc_bottle.png",
	MISC_BOX: "item/misc/misc_box.png",
	MISC_CRYSTAL: "item/misc/misc_crystal.png",
	MISC_FAN: "item/misc/misc_fan.png",
	MISC_FAN_INERT: "item/misc/misc_fan_inert.png",
	MISC_HORN: "item/misc/misc_horn.png",
	MISC_LAMP: "item/misc/misc_lamp.png",
	MISC_LAMP_INERT: "item/misc/misc_lamp_inert.png",
	MISC_LANTERN: "item/misc/misc_lantern.png",
	MISC_LIGHTNING_ROD: "item/misc/misc_lightning_rod.png",
	MISC_LIGHTNING_INERT: "item/misc/misc_lightning_rod_inert.png",
	MISC_ORB: "item/misc/misc_orb.png",
	MISC_ORB2: "item/misc/misc_orb2.png",
	MISC_PHANTOM_MIRROR: "item/misc/misc_phantom_mirror.png",
	MISC_PHIAL: "item/misc/misc_phial.png",
	MISC_PHIAL_INERT: "item/misc/misc_phial_inert.png",
	MISC_QUAD: "item/misc/misc_quad.png",
	MISC_SACK: "item/misc/misc_sack.png",
	MISC_STONE: "item/misc/misc_stone.png",
	MISC_STONE_INERT: "item/misc/misc_stone_inert.png",
	MISC_ZIGFIG: "item/misc/misc_zigfig.png",
	MISC_GENERIC: "item/misc/runes/generic.png",
	MISC_RUNE_ABYSS: "item/misc/runes/rune_abyss.png",
	MISC_RUNE_CEREBOV: "item/misc/runes/rune_cerebov.png",
	MISC_RUNE_COCYTUS: "item/misc/runes/rune_cocytus.png",
	MISC_RUNE_DEMONIC_1: "item/misc/runes/rune_demonic_1.png",
	MISC_RUNE_DEMONIC_2: "item/misc/runes/rune_demonic_2.png",
	MISC_RUNE_DEMONIC_3: "item/misc/runes/rune_demonic_3.png",
	MISC_RUNE_DEMONIC_4: "item/misc/runes/rune_demonic_4.png",
	MISC_RUNE_DEMONIC_5: "item/misc/runes/rune_demonic_5.png",
	MISC_RUNE_DEMONIC_6: "item/misc/runes/rune_demonic_6.png",
	MISC_RUNE_DIS: "item/misc/runes/rune_dis.png",
	MISC_RUNE_ELVEN: "item/misc/runes/rune_elven.png",
	MISC_RUNE_GEHENNA: "item/misc/runes/rune_gehenna.png",
	MISC_RUNE_GLOORX_VLOQ: "item/misc/runes/rune_gloorx_vloq.png",
	MISC_RUNE_LOM_LOBON: "item/misc/runes/rune_lom_lobon.png",
	MISC_RUNE_MNOLEG: "item/misc/runes/rune_mnoleg.png",
	MISC_RUNE_SHOALS: "item/misc/runes/rune_shoals.png",
	MISC_RUNE_SLIME: "item/misc/runes/rune_slime.png",
	MISC_RUNE_SNAKE: "item/misc/runes/rune_snake.png",
	MISC_RUNE_SPIDER: "item/misc/runes/rune_spider.png",
	MISC_RUNE_SWAMP: "item/misc/runes/rune_swamp.png",
	MISC_RUNE_TARTARUS: "item/misc/runes/rune_tartarus.png",
	MISC_RUNE_TOMB: "item/misc/runes/rune_tomb.png",
	MISC_RUNE_VAULTS: "item/misc/runes/rune_vaults.png",
	MISC_UNCOLLECTED_ORB: "item/misc/uncollected_orb.png",
	MISC_UNCOLLECTED_GENERIC: "item/misc/uncollected_runes/generic.png",
	MISC_UNCOLLECTED_RUNE_ABYSS: "item/misc/uncollected_runes/rune_abyss.png",
	MISC_UNCOLLECTED_RUNE_CEREBOV: "item/misc/uncollected_runes/rune_cerebov.png",
	MISC_UNCOLLECTED_RUNE_COCYTUS: "item/misc/uncollected_runes/rune_cocytus.png",
	MISC_UNCOLLECTED_RUNE_DEMONIC: "item/misc/uncollected_runes/rune_demonic.png",
	MISC_UNCOLLECTED_RUNE_DIS: "item/misc/uncollected_runes/rune_dis.png",
	MISC_UNCOLLECTED_RUNE_ELVEN: "item/misc/uncollected_runes/rune_elven.png",
	MISC_UNCOLLECTED_RUNE_GEHENNA: "item/misc/uncollected_runes/rune_gehenna.png",
	MISC_UNCOLLECTED_RUNE_GLOORX_VLOQ: "item/misc/uncollected_runes/rune_gloorx_vloq.png",
	MISC_UNCOLLECTED_RUNE_LOM_LOBON: "item/misc/uncollected_runes/rune_lom_lobon.png",
	MISC_UNCOLLECTED_RUNE_MNOLEG: "item/misc/uncollected_runes/rune_mnoleg.png",
	MISC_UNCOLLECTED_RUNE_SHOALS: "item/misc/uncollected_runes/rune_shoals.png",
	MISC_UNCOLLECTED_RUNE_SLIME: "item/misc/uncollected_runes/rune_slime.png",
	MISC_UNCOLLECTED_RUNE_SNAKE: "item/misc/uncollected_runes/rune_snake.png",
	MISC_UNCOLLECTED_RUNE_SPIDER: "item/misc/uncollected_runes/rune_spider.png",
	MISC_UNCOLLECTED_RUNE_SWAMP: "item/misc/uncollected_runes/rune_swamp.png",
	MISC_UNCOLLECTED_RUNE_TARTARUS: "item/misc/uncollected_runes/rune_tartarus.png",
	MISC_UNCOLLECTED_RUNE_TOMB: "item/misc/uncollected_runes/rune_tomb.png",
	MISC_UNCOLLECTED_RUNE_VAULTS: "item/misc/uncollected_runes/rune_vaults.png",
	POTION_BLACK: "item/potion/black.png",
	POTION_BRILLIANT_BLUE: "item/potion/brilliant_blue.png",
	POTION_BROWN: "item/potion/brown.png",
	POTION_BUBBLY: "item/potion/bubbly.png",
	POTION_CLOUDY: "item/potion/cloudy.png",
	POTION_CYAN: "item/potion/cyan.png",
	POTION_DARK: "item/potion/dark.png",
	POTION_EFFERVESCENT: "item/potion/effervescent.png",
	POTION_EMERALD: "item/potion/emerald.png",
	POTION_FIZZY: "item/potion/fizzy.png",
	POTION_GOLDEN: "item/potion/golden.png",
	POTION_AGILITY: "item/potion/i-agility.png",
	POTION_AMBROSIA: "item/potion/i-ambrosia.png",
	POTION_BERSERK_RAGE: "item/potion/i-berserk-rage.png",
	POTION_BLOOD: "item/potion/i-blood.png",
	POTION_BRILLIANCE: "item/potion/i-brilliance.png",
	POTION_CANCEL: "item/potion/i-cancel.png",
	POTION_COAGULATED_BLOOD: "item/potion/i-coagulated-blood.png",
	POTION_CONFUSION: "item/potion/i-confusion.png",
	POTION_CURE_MUTATION: "item/potion/i-cure-mutation.png",
	POTION_CURING: "item/potion/i-curing.png",
	POTION_DECAY: "item/potion/i-decay.png",
	POTION_DEGENERATION: "item/potion/i-degeneration.png",
	POTION_EXPERIENCE: "item/potion/i-experience.png",
	POTION_FLIGHT: "item/potion/i-flight.png",
	POTION_GAIN_DEXTERITY: "item/potion/i-gain-dexterity.png",
	POTION_GAIN_INTELLIGENCE: "item/potion/i-gain-intelligence.png",
	POTION_GAIN_STRENGTH: "item/potion/i-gain-strength.png",
	POTION_GOOD_MUTATION: "item/potion/i-good-mutation.png",
	POTION_HASTE: "item/potion/i-haste.png",
	POTION_HEAL_WOUNDS: "item/potion/i-heal-wounds.png",
	POTION_INVISIBILITY: "item/potion/i-invisibility.png",
	POTION_LABEL: "item/potion/i-label.png",
	POTION_LIGNIFY: "item/potion/i-lignify.png",
	POTION_MAGIC: "item/potion/i-magic.png",
	POTION_MIGHT: "item/potion/i-might.png",
	POTION_MUTATION: "item/potion/i-mutation.png",
	POTION_PARALYSIS: "item/potion/i-paralysis.png",
	POTION_POISON: "item/potion/i-poison.png",
	POTION_PORRIDGE: "item/potion/i-porridge.png",
	POTION_RESISTANCE: "item/potion/i-resistance.png",
	POTION_RESTORE_ABILITIES: "item/potion/i-restore-abilities.png",
	POTION_SLOWING: "item/potion/i-slowing.png",
	POTION_STRONG_POISON: "item/potion/i-strong-poison.png",
	POTION_MAGENTA: "item/potion/magenta.png",
	POTION_MURKY: "item/potion/murky.png",
	POTION_ORANGE: "item/potion/orange.png",
	POTION_PINK: "item/potion/pink.png",
	POTION_PUCE: "item/potion/puce.png",
	POTION_PURPLE_RED: "item/potion/purple_red.png",
	POTION_RUBY: "item/potion/ruby.png",
	POTION_SILVER: "item/potion/silver.png",
	POTION_SKY_BLUE: "item/potion/sky_blue.png",
	POTION_UNKNOWN: "item/potion/unknown.png",
	POTION_WHITE: "item/potion/white.png",
	POTION_YELLOW: "item/potion/yellow.png",
	RING_AGATE: "item/ring/agate.png",
	RING_ARTEFACT_MAGE: "item/ring/artefact/urand_mage.png",
	RING_ARTEFACT_OCTORING: "item/ring/artefact/urand_octoring.png",
	RING_ARTEFACT_PHASING: "item/ring/artefact/urand_phasing.png",
	RING_ARTEFACT_ROBUSTNESS: "item/ring/artefact/urand_robustness.png",
	RING_ARTEFACT_SHADOWS: "item/ring/artefact/urand_shadows.png",
	RING_BRASS: "item/ring/brass.png",
	RING_BRONZE: "item/ring/bronze.png",
	RING_CLAY: "item/ring/clay.png",
	RING_COPPER: "item/ring/copper.png",
	RING_CORAL: "item/ring/coral.png",
	RING_DIAMOND: "item/ring/diamond.png",
	RING_EMERALD: "item/ring/emerald.png",
	RING_GLASS: "item/ring/glass.png",
	RING_GOLD: "item/ring/gold.png",
	RING_GOLD_BLUE: "item/ring/gold_blue.png",
	RING_GOLD_GREEN: "item/ring/gold_green.png",
	RING_GOLD_RED: "item/ring/gold_red.png",
	RING_GRANITE: "item/ring/granite.png",
	RING_ATTENTION: "item/ring/i-attention.png",
	RING_C_TELEPORT: "item/ring/i-c-teleport.png",
	RING_DEX: "item/ring/i-dex.png",
	RING_EVASION: "item/ring/i-evasion.png",
	RING_FIRE: "item/ring/i-fire.png",
	RING_FLIGHT: "item/ring/i-flight.png",
	RING_ICE: "item/ring/i-ice.png",
	RING_INT: "item/ring/i-int.png",
	RING_LIFE_PROTECTION: "item/ring/i-life-protection.png",
	RING_MAGICAL_POWER: "item/ring/i-magical-power.png",
	RING_PROTECTION: "item/ring/i-protection.png",
	RING_R_COLD: "item/ring/i-r-cold.png",
	RING_R_CORROSION: "item/ring/i-r-corrosion.png",
	RING_R_FIRE: "item/ring/i-r-fire.png",
	RING_R_MAGIC: "item/ring/i-r-magic.png",
	RING_R_POISON: "item/ring/i-r-poison.png",
	RING_S_ATTR: "item/ring/i-s-attr.png",
	RING_SEE_INVIS: "item/ring/i-see-invis.png",
	RING_SLAYING: "item/ring/i-slaying.png",
	RING_STEALTH: "item/ring/i-stealth.png",
	RING_STR: "item/ring/i-str.png",
	RING_TELEPORT: "item/ring/i-teleport.png",
	RING_WIZARDRY: "item/ring/i-wizardry.png",
	RING_IRON: "item/ring/iron.png",
	RING_IVORY: "item/ring/ivory.png",
	RING_JADE: "item/ring/jade.png",
	RING_MOONSTONE: "item/ring/moonstone.png",
	RING_OPAL: "item/ring/opal.png",
	RING_PEARL: "item/ring/pearl.png",
	RING_PLAIN_BLACK: "item/ring/plain_black.png",
	RING_PLAIN_RED: "item/ring/plain_red.png",
	RING_PLAIN_YELLOW: "item/ring/plain_yellow.png",
	RING_RANDARTS_ANVIL: "item/ring/randarts/anvil.png",
	RING_RANDARTS_BLOOD: "item/ring/randarts/blood.png",
	RING_RANDARTS_BRONZE_FLOWER: "item/ring/randarts/bronze-flower.png",
	RING_RANDARTS_DARK: "item/ring/randarts/dark.png",
	RING_RANDARTS_DOUBLE: "item/ring/randarts/double.png",
	RING_RANDARTS_EYE: "item/ring/randarts/eye.png",
	RING_RANDARTS_FIRE: "item/ring/randarts/fire.png",
	RING_RANDARTS_FLOWER: "item/ring/randarts/flower.png",
	RING_RANDARTS_FOUR_COLOUR: "item/ring/randarts/four-colour.png",
	RING_RANDARTS_GREEN: "item/ring/randarts/green.png",
	RING_RANDARTS_ICE: "item/ring/randarts/ice.png",
	RING_RANDARTS_PINK: "item/ring/randarts/pink.png",
	RING_RANDARTS_RED_BLUE: "item/ring/randarts/red-blue.png",
	RING_RANDARTS_SNAKE: "item/ring/randarts/snake.png",
	RING_RANDARTS_ZIRCON: "item/ring/randarts/zircon.png",
	RING_RUBY: "item/ring/ruby.png",
	RING_SILVER: "item/ring/silver.png",
	RING_STEEL: "item/ring/steel.png",
	RING_TIGER_EYE: "item/ring/tiger_eye.png",
	RING_TOURMALINE: "item/ring/tourmaline.png",
	RING_WOODEN: "item/ring/wooden.png",
	ROD00: "item/rod/rod00.png",
	ROD01: "item/rod/rod01.png",
	ROD02: "item/rod/rod02.png",
	ROD03: "item/rod/rod03.png",
	ROD04: "item/rod/rod04.png",
	ROD05: "item/rod/rod05.png",
	ROD06: "item/rod/rod06.png",
	ROD07: "item/rod/rod07.png",
	ROD08: "item/rod/rod08.png",
	ROD09: "item/rod/rod09.png",
	SCROLL_ACQUIREMENT: "item/scroll/i-acquirement.png",
	SCROLL_AMNESIA: "item/scroll/i-amnesia.png",
	SCROLL_BLINKING: "item/scroll/i-blinking.png",
	SCROLL_BRAND_WEAPON: "item/scroll/i-brand-weapon.png",
	SCROLL_CURSE_JEWELLERY: "item/scroll/i-curse-jewellery.png",
	SCROLL_CURSE_ARMOUR: "item/scroll/i-curse_armour.png",
	SCROLL_CURSE_WEAPON: "item/scroll/i-curse_weapon.png",
	SCROLL_ENCHANT_WEAPON: "item/scroll/i-enchant-weapon.png",
	SCROLL_ENCHANT_ARMOUR: "item/scroll/i-enchant_armour.png",
	SCROLL_FEAR: "item/scroll/i-fear.png",
	SCROLL_FOG: "item/scroll/i-fog.png",
	SCROLL_HOLY_WORD: "item/scroll/i-holy_word.png",
	SCROLL_IDENTIFY: "item/scroll/i-identify.png",
	SCROLL_IMMOLATION: "item/scroll/i-immolation.png",
	SCROLL_MAGIC_MAPPING: "item/scroll/i-magic_mapping.png",
	SCROLL_NOISE: "item/scroll/i-noise.png",
	SCROLL_RANDOM_USELESSNESS: "item/scroll/i-random_uselessness.png",
	SCROLL_RECHARGING: "item/scroll/i-recharging.png",
	SCROLL_REMOVE_CURSE: "item/scroll/i-remove_curse.png",
	SCROLL_SILENCE: "item/scroll/i-silence.png",
	SCROLL_TELEPORTATION: "item/scroll/i-teleportation.png",
	SCROLL_TORMENT: "item/scroll/i-torment.png",
	SCROLL_UNHOLY_CREATION: "item/scroll/i-unholy_creation.png",
	SCROLL_VULNERABILITY: "item/scroll/i-vulnerability.png",
	SCROLL_BLUE: "item/scroll/scroll-blue.png",
	SCROLL_BROWN: "item/scroll/scroll-brown.png",
	SCROLL_CYAN: "item/scroll/scroll-cyan.png",
	SCROLL_GREEN: "item/scroll/scroll-green.png",
	SCROLL_GREY: "item/scroll/scroll-grey.png",
	SCROLL_PURPLE: "item/scroll/scroll-purple.png",
	SCROLL_RED: "item/scroll/scroll-red.png",
	SCROLL_YELLOW: "item/scroll/scroll-yellow.png",
	SCROLL_SCROLL: "item/scroll/scroll.png",
	STAFF_AIR: "item/staff/i-staff_air.png",
	STAFF_CHANNELING: "item/staff/i-staff_channeling.png",
	STAFF_COLD: "item/staff/i-staff_cold.png",
	STAFF_CONJURATION: "item/staff/i-staff_conjuration.png",
	STAFF_DEATH: "item/staff/i-staff_death.png",
	STAFF_EARTH: "item/staff/i-staff_earth.png",
	STAFF_ENCHANTMENT: "item/staff/i-staff_enchantment.png",
	STAFF_ENERGY: "item/staff/i-staff_energy.png",
	STAFF_FIRE: "item/staff/i-staff_fire.png",
	STAFF_POISON: "item/staff/i-staff_poison.png",
	STAFF_POWER: "item/staff/i-staff_power.png",
	STAFF_SUMMONING: "item/staff/i-staff_summoning.png",
	STAFF_WIZARDRY: "item/staff/i-staff_wizardry.png",
	STAFF_STAFF00: "item/staff/staff00.png",
	STAFF_STAFF01: "item/staff/staff01.png",
	STAFF_STAFF02: "item/staff/staff02.png",
	STAFF_STAFF03: "item/staff/staff03.png",
	STAFF_STAFF04: "item/staff/staff04.png",
	STAFF_STAFF05: "item/staff/staff05.png",
	STAFF_STAFF06: "item/staff/staff06.png",
	STAFF_STAFF07: "item/staff/staff07.png",
	STAFF_STAFF08: "item/staff/staff08.png",
	STAFF_STAFF09: "item/staff/staff09.png",
	WAND_GEM_BONE: "item/wand/gem_bone.png",
	WAND_GEM_BRASS: "item/wand/gem_brass.png",
	WAND_GEM_BRONZE: "item/wand/gem_bronze.png",
	WAND_GEM_COPPER: "item/wand/gem_copper.png",
	WAND_GEM_GLASS: "item/wand/gem_glass.png",
	WAND_GEM_GOLD: "item/wand/gem_gold.png",
	WAND_GEM_IRON: "item/wand/gem_iron.png",
	WAND_GEM_IVORY: "item/wand/gem_ivory.png",
	WAND_GEM_LEAD: "item/wand/gem_lead.png",
	WAND_GEM_PLASTIC: "item/wand/gem_plastic.png",
	WAND_GEM_SILVER: "item/wand/gem_silver.png",
	WAND_GEM_WOOD: "item/wand/gem_wood.png",
	WAND_ACID: "item/wand/i-acid.png",
	WAND_CLOUDS: "item/wand/i-clouds.png",
	WAND_CONFUSION: "item/wand/i-confusion.png",
	WAND_DIGGING: "item/wand/i-digging.png",
	WAND_DISINTEGRATION: "item/wand/i-disintegration.png",
	WAND_ENSLAVEMENT: "item/wand/i-enslavement.png",
	WAND_FLAME: "item/wand/i-flame.png",
	WAND_HASTING: "item/wand/i-hasting.png",
	WAND_HEAL_WOUNDS: "item/wand/i-heal_wounds.png",
	WAND_ICEBLAST: "item/wand/i-iceblast.png",
	WAND_LIGHTNING: "item/wand/i-lightning.png",
	WAND_PARALYSIS: "item/wand/i-paralysis.png",
	WAND_POLYMORPH: "item/wand/i-polymorph.png",
	WAND_RANDOM_EFFECTS: "item/wand/i-random_effects.png",
	WAND_SCATTERSHOT: "item/wand/i-scattershot.png",
	WAND_SLOWING: "item/wand/i-slowing.png",
	WAND_TELEPORTATION: "item/wand/i-teleportation.png",
	WEAPON_ARTEFACT_DEMON_AXE: "item/weapon/artefact/spwpn_demon_axe.png",
	WEAPON_ARTEFACT_GLAIVE_OF_PRUNE: "item/weapon/artefact/spwpn_glaive_of_prune.png",
	WEAPON_ARTEFACT_MACE_OF_VARIABILITY: "item/weapon/artefact/spwpn_mace_of_variability.png",
	WEAPON_ARTEFACT_MAJIN: "item/weapon/artefact/spwpn_majin.png",
	WEAPON_ARTEFACT_SCEPTRE_OF_ASMODEUS: "item/weapon/artefact/spwpn_sceptre_of_asmodeus.png",
	WEAPON_ARTEFACT_SCEPTRE_OF_TORMENT: "item/weapon/artefact/spwpn_sceptre_of_torment.png",
	WEAPON_ARTEFACT_SCYTHE_OF_CURSES: "item/weapon/artefact/spwpn_scythe_of_curses.png",
	WEAPON_ARTEFACT_SINGING_SWORD: "item/weapon/artefact/spwpn_singing_sword.png",
	WEAPON_ARTEFACT_STAFF_OF_DISPATER: "item/weapon/artefact/spwpn_staff_of_dispater.png",
	WEAPON_ARTEFACT_STAFF_OF_OLGREB: "item/weapon/artefact/spwpn_staff_of_olgreb.png",
	WEAPON_ARTEFACT_SWORD_OF_CEREBOV: "item/weapon/artefact/spwpn_sword_of_cerebov.png",
	WEAPON_ARTEFACT_SWORD_OF_POWER: "item/weapon/artefact/spwpn_sword_of_power.png",
	WEAPON_ARTEFACT_SWORD_OF_ZONGULDROK: "item/weapon/artefact/spwpn_sword_of_zonguldrok.png",
	WEAPON_ARTEFACT_VAMPIRES_TOOTH: "item/weapon/artefact/spwpn_vampires_tooth.png",
	WEAPON_ARTEFACT_WRATH_OF_TROG: "item/weapon/artefact/spwpn_wrath_of_trog.png",
	WEAPON_ARTEFACT_WUCAD_MU: "item/weapon/artefact/spwpn_wucad_mu.png",
	WEAPON_ARTEFACT_ZEALOT_SWORD: "item/weapon/artefact/unrand_zealot_sword.png",
	WEAPON_ARTEFACT_ARC_BLADE: "item/weapon/artefact/urand_arc_blade.png",
	WEAPON_ARTEFACT_ARGA: "item/weapon/artefact/urand_arga.png",
	WEAPON_ARTEFACT_AXE_OF_WOE: "item/weapon/artefact/urand_axe_of_woe.png",
	WEAPON_ARTEFACT_BLOODBANE: "item/weapon/artefact/urand_bloodbane.png",
	WEAPON_ARTEFACT_BLOWGUN: "item/weapon/artefact/urand_blowgun.png",
	WEAPON_ARTEFACT_BOTONO: "item/weapon/artefact/urand_botono.png",
	WEAPON_ARTEFACT_BRILLIANCE: "item/weapon/artefact/urand_brilliance.png",
	WEAPON_ARTEFACT_CHILLY_DEATH: "item/weapon/artefact/urand_chilly_death.png",
	WEAPON_ARTEFACT_CRYSTAL_SPEAR: "item/weapon/artefact/urand_crystal_spear.png",
	WEAPON_ARTEFACT_CUTLASS: "item/weapon/artefact/urand_cutlass.png",
	WEAPON_ARTEFACT_DAMNATION: "item/weapon/artefact/urand_damnation.png",
	WEAPON_ARTEFACT_DARK_MAUL: "item/weapon/artefact/urand_dark_maul.png",
	WEAPON_ARTEFACT_DOOM_KNIGHT: "item/weapon/artefact/urand_doom_knight.png",
	WEAPON_ARTEFACT_ELEMENTAL: "item/weapon/artefact/urand_elemental.png",
	WEAPON_ARTEFACT_EOS: "item/weapon/artefact/urand_eos.png",
	WEAPON_ARTEFACT_FINISHER: "item/weapon/artefact/urand_finisher.png",
	WEAPON_ARTEFACT_FIRESTARTER: "item/weapon/artefact/urand_firestarter.png",
	WEAPON_ARTEFACT_FLAMING_DEATH: "item/weapon/artefact/urand_flaming_death.png",
	WEAPON_ARTEFACT_FROSTBITE: "item/weapon/artefact/urand_frostbite.png",
	WEAPON_ARTEFACT_GUARD: "item/weapon/artefact/urand_guard.png",
	WEAPON_ARTEFACT_GYRE: "item/weapon/artefact/urand_gyre.png",
	WEAPON_ARTEFACT_KATANA: "item/weapon/artefact/urand_katana.png",
	WEAPON_ARTEFACT_KNIFE_OF_ACCURACY: "item/weapon/artefact/urand_knife_of_accuracy.png",
	WEAPON_ARTEFACT_LEECH: "item/weapon/artefact/urand_leech.png",
	WEAPON_ARTEFACT_MORG: "item/weapon/artefact/urand_morg.png",
	WEAPON_ARTEFACT_OCTOPUS_KING: "item/weapon/artefact/urand_octopus_king.png",
	WEAPON_ARTEFACT_ORDER: "item/weapon/artefact/urand_order.png",
	WEAPON_ARTEFACT_PIERCER: "item/weapon/artefact/urand_piercer.png",
	WEAPON_ARTEFACT_PLUTONIUM: "item/weapon/artefact/urand_plutonium.png",
	WEAPON_ARTEFACT_PUNK: "item/weapon/artefact/urand_punk.png",
	WEAPON_ARTEFACT_RIFT: "item/weapon/artefact/urand_rift.png",
	WEAPON_ARTEFACT_SHILLELAGH: "item/weapon/artefact/urand_shillelagh.png",
	WEAPON_ARTEFACT_SKULLCRUSHER: "item/weapon/artefact/urand_skullcrusher.png",
	WEAPON_ARTEFACT_SNAKEBITE: "item/weapon/artefact/urand_snakebite.png",
	WEAPON_ARTEFACT_SNIPER: "item/weapon/artefact/urand_sniper.png",
	WEAPON_ARTEFACT_SPELLBINDER: "item/weapon/artefact/urand_spellbinder.png",
	WEAPON_ARTEFACT_SPRIGGANS_KNIFE: "item/weapon/artefact/urand_spriggans_knife.png",
	WEAPON_ARTEFACT_STORM_BOW: "item/weapon/artefact/urand_storm_bow.png",
	WEAPON_ARTEFACT_THERMIC_ENGINE: "item/weapon/artefact/urand_thermic_engine.png",
	WEAPON_ARTEFACT_UNDEADHUNTER: "item/weapon/artefact/urand_undeadhunter.png",
	WEAPON_ARTEFACT_WYRMBANE: "item/weapon/artefact/urand_wyrmbane.png",
	WEAPON_ARTEFACT_WYRMBANE1: "item/weapon/artefact/urand_wyrmbane1.png",
	WEAPON_ARTEFACT_WYRMBANE2: "item/weapon/artefact/urand_wyrmbane2.png",
	WEAPON_ARTEFACT_WYRMBANE3: "item/weapon/artefact/urand_wyrmbane3.png",
	WEAPON_ARTEFACT_WYRMBANE4: "item/weapon/artefact/urand_wyrmbane4.png",
	WEAPON_ARTEFACT_ZEPHYR: "item/weapon/artefact/urand_zephyr.png",
	WEAPON_BARDICHE1: "item/weapon/bardiche1.png",
	WEAPON_BARDICHE2: "item/weapon/bardiche2.png",
	WEAPON_BARDICHE3: "item/weapon/bardiche3.png",
	WEAPON_BATTLE_AXE1: "item/weapon/battle_axe1.png",
	WEAPON_BATTLE_AXE2: "item/weapon/battle_axe2.png",
	WEAPON_BATTLE_AXE3: "item/weapon/battle_axe3.png",
	WEAPON_BLESSED_BLADE: "item/weapon/blessed_blade.png",
	WEAPON_BRANDS_ANTIMAGIC: "item/weapon/brands/i-antimagic.png",
	WEAPON_BRANDS_CHAOS: "item/weapon/brands/i-chaos.png",
	WEAPON_BRANDS_CONFUSION: "item/weapon/brands/i-confusion.png",
	WEAPON_BRANDS_CURARE: "item/weapon/brands/i-curare.png",
	WEAPON_BRANDS_DISPERSAL: "item/weapon/brands/i-dispersal.png",
	WEAPON_BRANDS_DISTORTION: "item/weapon/brands/i-distortion.png",
	WEAPON_BRANDS_DRAINING: "item/weapon/brands/i-draining.png",
	WEAPON_BRANDS_ELECTROCUTION: "item/weapon/brands/i-electrocution.png",
	WEAPON_BRANDS_EVASION: "item/weapon/brands/i-evasion.png",
	WEAPON_BRANDS_EXPLOSION: "item/weapon/brands/i-explosion.png",
	WEAPON_BRANDS_FLAMING: "item/weapon/brands/i-flaming.png",
	WEAPON_BRANDS_FREEZING: "item/weapon/brands/i-freezing.png",
	WEAPON_BRANDS_FRENZY: "item/weapon/brands/i-frenzy.png",
	WEAPON_BRANDS_HOLY_WRATH: "item/weapon/brands/i-holy_wrath.png",
	WEAPON_BRANDS_PAIN: "item/weapon/brands/i-pain.png",
	WEAPON_BRANDS_PARALYSIS: "item/weapon/brands/i-paralysis.png",
	WEAPON_BRANDS_PENETRATION: "item/weapon/brands/i-penetration.png",
	WEAPON_BRANDS_PROTECTION: "item/weapon/brands/i-protection.png",
	WEAPON_BRANDS_REAPING: "item/weapon/brands/i-reaping.png",
	WEAPON_BRANDS_RETURNING: "item/weapon/brands/i-returning.png",
	WEAPON_BRANDS_SICKNESS: "item/weapon/brands/i-sickness.png",
	WEAPON_BRANDS_SLEEP: "item/weapon/brands/i-sleep.png",
	WEAPON_BRANDS_SLOWING: "item/weapon/brands/i-slowing.png",
	WEAPON_BRANDS_SPEED: "item/weapon/brands/i-speed.png",
	WEAPON_BRANDS_VAMPIRISM: "item/weapon/brands/i-vampirism.png",
	WEAPON_BRANDS_VENOM: "item/weapon/brands/i-venom.png",
	WEAPON_BRANDS_VORPAL: "item/weapon/brands/i-vorpal.png",
	WEAPON_BROAD_AXE1: "item/weapon/broad_axe1.png",
	WEAPON_BROAD_AXE2: "item/weapon/broad_axe2.png",
	WEAPON_BROAD_AXE3: "item/weapon/broad_axe3.png",
	WEAPON_BULLWHIP: "item/weapon/bullwhip.png",
	WEAPON_BULLWHIP2: "item/weapon/bullwhip2.png",
	WEAPON_BULLWHIP3: "item/weapon/bullwhip3.png",
	WEAPON_CLUB: "item/weapon/club.png",
	WEAPON_CLUB2: "item/weapon/club2.png",
	WEAPON_DAGGER: "item/weapon/dagger.png",
	WEAPON_DAGGER2: "item/weapon/dagger2.png",
	WEAPON_DAGGER3: "item/weapon/dagger3.png",
	WEAPON_DEMON_BLADE: "item/weapon/demon_blade.png",
	WEAPON_DEMON_BLADE2: "item/weapon/demon_blade2.png",
	WEAPON_DEMON_BLADE3: "item/weapon/demon_blade3.png",
	WEAPON_DEMON_TRIDENT: "item/weapon/demon_trident.png",
	WEAPON_DEMON_TRIDENT2: "item/weapon/demon_trident2.png",
	WEAPON_DEMON_TRIDENT3: "item/weapon/demon_trident3.png",
	WEAPON_DEMON_WHIP: "item/weapon/demon_whip.png",
	WEAPON_DEMON_WHIP2: "item/weapon/demon_whip2.png",
	WEAPON_DEMON_WHIP3: "item/weapon/demon_whip3.png",
	WEAPON_DIRE_FLAIL1: "item/weapon/dire_flail1.png",
	WEAPON_DIRE_FLAIL2: "item/weapon/dire_flail2.png",
	WEAPON_DIRE_FLAIL3: "item/weapon/dire_flail3.png",
	WEAPON_DOUBLE_SWORD: "item/weapon/double_sword.png",
	WEAPON_DOUBLE_SWORD2: "item/weapon/double_sword2.png",
	WEAPON_DOUBLE_SWORD3: "item/weapon/double_sword3.png",
	WEAPON_EVENINGSTAR1: "item/weapon/eveningstar1.png",
	WEAPON_EVENINGSTAR2: "item/weapon/eveningstar2.png",
	WEAPON_EVENINGSTAR3: "item/weapon/eveningstar3.png",
	WEAPON_EXECUTIONER_AXE1: "item/weapon/executioner_axe1.png",
	WEAPON_EXECUTIONER_AXE2: "item/weapon/executioner_axe2.png",
	WEAPON_EXECUTIONER_AXE3: "item/weapon/executioner_axe3.png",
	WEAPON_FALCHION1: "item/weapon/falchion1.png",
	WEAPON_FALCHION2: "item/weapon/falchion2.png",
	WEAPON_FALCHION3: "item/weapon/falchion3.png",
	WEAPON_FLAIL1: "item/weapon/flail1.png",
	WEAPON_FLAIL2: "item/weapon/flail2.png",
	WEAPON_FLAIL3: "item/weapon/flail3.png",
	WEAPON_GIANT_CLUB: "item/weapon/giant_club.png",
	WEAPON_GIANT_CLUB2: "item/weapon/giant_club2.png",
	WEAPON_GIANT_CLUB3: "item/weapon/giant_club3.png",
	WEAPON_GIANT_SPIKED_CLUB: "item/weapon/giant_spiked_club.png",
	WEAPON_GIANT_SPIKED_CLUB2: "item/weapon/giant_spiked_club2.png",
	WEAPON_GIANT_SPIKED_CLUB3: "item/weapon/giant_spiked_club3.png",
	WEAPON_GLAIVE1: "item/weapon/glaive1.png",
	WEAPON_GLAIVE2: "item/weapon/glaive2.png",
	WEAPON_GLAIVE3: "item/weapon/glaive3.png",
	WEAPON_GREATSWORD1: "item/weapon/greatsword1.png",
	WEAPON_GREATSWORD2: "item/weapon/greatsword2.png",
	WEAPON_GREATSWORD3: "item/weapon/greatsword3.png",
	WEAPON_HALBERD1: "item/weapon/halberd1.png",
	WEAPON_HALBERD2: "item/weapon/halberd2.png",
	WEAPON_HALBERD3: "item/weapon/halberd3.png",
	WEAPON_HAND_AXE1: "item/weapon/hand_axe1.png",
	WEAPON_HAND_AXE2: "item/weapon/hand_axe2.png",
	WEAPON_HAND_AXE3: "item/weapon/hand_axe3.png",
	WEAPON_LAJATANG1: "item/weapon/lajatang1.png",
	WEAPON_LAJATANG2: "item/weapon/lajatang2.png",
	WEAPON_LAJATANG3: "item/weapon/lajatang3.png",
	WEAPON_LONG_SWORD1: "item/weapon/long_sword1.png",
	WEAPON_LONG_SWORD2: "item/weapon/long_sword2.png",
	WEAPON_LONG_SWORD3: "item/weapon/long_sword3.png",
	WEAPON_MACE1: "item/weapon/mace1.png",
	WEAPON_MACE2: "item/weapon/mace2.png",
	WEAPON_MACE3: "item/weapon/mace3.png",
	WEAPON_MACE_LARGE1: "item/weapon/mace_large1.png",
	WEAPON_MACE_LARGE2: "item/weapon/mace_large2.png",
	WEAPON_MACE_LARGE3: "item/weapon/mace_large3.png",
	WEAPON_MORNINGSTAR1: "item/weapon/morningstar1.png",
	WEAPON_MORNINGSTAR2: "item/weapon/morningstar2.png",
	WEAPON_MORNINGSTAR3: "item/weapon/morningstar3.png",
	WEAPON_QUARTERSTAFF: "item/weapon/quarterstaff.png",
	WEAPON_QUARTERSTAFF2: "item/weapon/quarterstaff2.png",
	WEAPON_QUARTERSTAFF3: "item/weapon/quarterstaff3.png",
	WEAPON_QUICKBLADE1: "item/weapon/quickblade1.png",
	WEAPON_QUICKBLADE2: "item/weapon/quickblade2.png",
	WEAPON_QUICKBLADE3: "item/weapon/quickblade3.png",
	WEAPON_ARBALEST1: "item/weapon/ranged/arbalest1.png",
	WEAPON_ARBALEST2: "item/weapon/ranged/arbalest2.png",
	WEAPON_ARBALEST3: "item/weapon/ranged/arbalest3.png",
	WEAPON_ARROW1: "item/weapon/ranged/arrow1.png",
	WEAPON_ARROW2: "item/weapon/ranged/arrow2.png",
	WEAPON_BLOWGUN1: "item/weapon/ranged/blowgun1.png",
	WEAPON_BLOWGUN2: "item/weapon/ranged/blowgun2.png",
	WEAPON_CROSSBOW_BOLT1: "item/weapon/ranged/crossbow_bolt1.png",
	WEAPON_CROSSBOW_BOLT2: "item/weapon/ranged/crossbow_bolt2.png",
	WEAPON_FUSTIBALUS1: "item/weapon/ranged/fustibalus1.png",
	WEAPON_FUSTIBALUS2: "item/weapon/ranged/fustibalus2.png",
	WEAPON_FUSTIBALUS3: "item/weapon/ranged/fustibalus3.png",
	WEAPON_HAND_CROSSBOW: "item/weapon/ranged/hand_crossbow.png",
	WEAPON_HAND_CROSSBOW2: "item/weapon/ranged/hand_crossbow2.png",
	WEAPON_HAND_CROSSBOW3: "item/weapon/ranged/hand_crossbow3.png",
	WEAPON_JAVELIN1: "item/weapon/ranged/javelin1.png",
	WEAPON_JAVELIN2: "item/weapon/ranged/javelin2.png",
	WEAPON_LONGBOW1: "item/weapon/ranged/longbow1.png",
	WEAPON_LONGBOW2: "item/weapon/ranged/longbow2.png",
	WEAPON_LONGBOW3: "item/weapon/ranged/longbow3.png",
	WEAPON_NEEDLE_C: "item/weapon/ranged/needle-c.png",
	WEAPON_NEEDLE_P: "item/weapon/ranged/needle-p.png",
	WEAPON_NEEDLE1: "item/weapon/ranged/needle1.png",
	WEAPON_NEEDLE2: "item/weapon/ranged/needle2.png",
	WEAPON_ROCK: "item/weapon/ranged/rock.png",
	WEAPON_SHORTBOW1: "item/weapon/ranged/shortbow1.png",
	WEAPON_SHORTBOW2: "item/weapon/ranged/shortbow2.png",
	WEAPON_SHORTBOW3: "item/weapon/ranged/shortbow3.png",
	WEAPON_SILVER_ARROW1: "item/weapon/ranged/silver_arrow1.png",
	WEAPON_SILVER_ARROW2: "item/weapon/ranged/silver_arrow2.png",
	WEAPON_SILVER_CROSSBOW_BOLT1: "item/weapon/ranged/silver_crossbow_bolt1.png",
	WEAPON_SILVER_CROSSBOW_BOLT2: "item/weapon/ranged/silver_crossbow_bolt2.png",
	WEAPON_SILVER_JAVELIN1: "item/weapon/ranged/silver_javelin1.png",
	WEAPON_SILVER_JAVELIN2: "item/weapon/ranged/silver_javelin2.png",
	WEAPON_SILVER_SLING_BULLET1: "item/weapon/ranged/silver_sling_bullet1.png",
	WEAPON_SILVER_SLING_BULLET2: "item/weapon/ranged/silver_sling_bullet2.png",
	WEAPON_SILVER_TOMAHAWK: "item/weapon/ranged/silver_tomahawk.png",
	WEAPON_SLING1: "item/weapon/ranged/sling1.png",
	WEAPON_SLING2: "item/weapon/ranged/sling2.png",
	WEAPON_SLING3: "item/weapon/ranged/sling3.png",
	WEAPON_SLING_BULLET1: "item/weapon/ranged/sling_bullet1.png",
	WEAPON_SLING_BULLET2: "item/weapon/ranged/sling_bullet2.png",
	WEAPON_STEEL_ARROW1: "item/weapon/ranged/steel_arrow1.png",
	WEAPON_STEEL_ARROW2: "item/weapon/ranged/steel_arrow2.png",
	WEAPON_STEEL_CROSSBOW_BOLT1: "item/weapon/ranged/steel_crossbow_bolt1.png",
	WEAPON_STEEL_CROSSBOW_BOLT2: "item/weapon/ranged/steel_crossbow_bolt2.png",
	WEAPON_STEEL_JAVELIN1: "item/weapon/ranged/steel_javelin1.png",
	WEAPON_STEEL_JAVELIN2: "item/weapon/ranged/steel_javelin2.png",
	WEAPON_STEEL_SLING_BULLET1: "item/weapon/ranged/steel_sling_bullet1.png",
	WEAPON_STEEL_SLING_BULLET2: "item/weapon/ranged/steel_sling_bullet2.png",
	WEAPON_STEEL_TOMAHAWK: "item/weapon/ranged/steel_tomahawk.png",
	WEAPON_STONE: "item/weapon/ranged/stone.png",
	WEAPON_THROWING_NET: "item/weapon/ranged/throwing_net.png",
	WEAPON_TOMAHAWK1: "item/weapon/ranged/tomahawk1.png",
	WEAPON_TOMAHAWK2: "item/weapon/ranged/tomahawk2.png",
	WEAPON_TRIPLE_CROSSBOW: "item/weapon/ranged/triple_crossbow.png",
	WEAPON_TRIPLE_CROSSBOW2: "item/weapon/ranged/triple_crossbow2.png",
	WEAPON_RAPIER1: "item/weapon/rapier1.png",
	WEAPON_RAPIER2: "item/weapon/rapier2.png",
	WEAPON_RAPIER3: "item/weapon/rapier3.png",
	WEAPON_SACRED_SCOURGE: "item/weapon/sacred_scourge.png",
	WEAPON_SCIMITAR1: "item/weapon/scimitar1.png",
	WEAPON_SCIMITAR2: "item/weapon/scimitar2.png",
	WEAPON_SCIMITAR3: "item/weapon/scimitar3.png",
	WEAPON_SCYTHE1: "item/weapon/scythe1.png",
	WEAPON_SCYTHE2: "item/weapon/scythe2.png",
	WEAPON_SCYTHE3: "item/weapon/scythe3.png",
	WEAPON_SHORT_SWORD1: "item/weapon/short_sword1.png",
	WEAPON_SHORT_SWORD2: "item/weapon/short_sword2.png",
	WEAPON_SHORT_SWORD3: "item/weapon/short_sword3.png",
	WEAPON_SPEAR1: "item/weapon/spear1.png",
	WEAPON_SPEAR2: "item/weapon/spear2.png",
	WEAPON_SPEAR3: "item/weapon/spear3.png",
	WEAPON_STAFF: "item/weapon/staff.png",
	WEAPON_STAFF_MUMMY: "item/weapon/staff_mummy.png",
	WEAPON_TRIDENT1: "item/weapon/trident1.png",
	WEAPON_TRIDENT2: "item/weapon/trident2.png",
	WEAPON_TRIDENT3: "item/weapon/trident3.png",
	WEAPON_TRIPLE_SWORD: "item/weapon/triple_sword.png",
	WEAPON_TRIPLE_SWORD2: "item/weapon/triple_sword2.png",
	WEAPON_TRIPLE_SWORD3: "item/weapon/triple_sword3.png",
	WEAPON_TRISHULA: "item/weapon/trishula.png",
	WEAPON_WAR_AXE1: "item/weapon/war_axe1.png",
	WEAPON_WAR_AXE2: "item/weapon/war_axe2.png",
	WEAPON_WAR_AXE3: "item/weapon/war_axe3.png",
};