interface ImiscTiles {
	[key: string]: string
	BLOOD_GREEN: string;
	BLOOD_GREEN1: string;
	BLOOD_GREEN2: string;
	BLOOD_GREEN3: string;
	BLOOD_GREEN4: string;
	BLOOD_PUDDLE_RED: string;
	BLOOD_PUDDLE_RED1: string;
	BLOOD_PUDDLE_RED2: string;
	BLOOD_PUDDLE_RED3: string;
	BLOOD_PUDDLE_RED4: string;
	BLOOD_RED00: string;
	BLOOD_RED01: string;
	BLOOD_RED02: string;
	BLOOD_RED03: string;
	BLOOD_RED04: string;
	BLOOD_RED05: string;
	BLOOD_RED06: string;
	BLOOD_RED07: string;
	BLOOD_RED08: string;
	BLOOD_RED09: string;
	BLOOD_RED10: string;
	BLOOD_RED11: string;
	BLOOD_RED12: string;
	BLOOD_RED13: string;
	BLOOD_RED14: string;
	BLOOD_RED15: string;
	BLOOD_RED16: string;
	BLOOD_RED17: string;
	BLOOD_RED18: string;
	BLOOD_RED19: string;
	BLOOD_RED20: string;
	BLOOD_RED21: string;
	BLOOD_RED22: string;
	BLOOD_RED23: string;
	BLOOD_RED24: string;
	BLOOD_RED25: string;
	BLOOD_RED26: string;
	BLOOD_RED27: string;
	BLOOD_RED28: string;
	BLOOD_RED29: string;
	BLOOD_WALL_BLOOD00_E: string;
	BLOOD_WALL_BLOOD00_N: string;
	BLOOD_WALL_BLOOD00_S: string;
	BLOOD_WALL_BLOOD00_W: string;
	BLOOD_WALL_BLOOD01_E: string;
	BLOOD_WALL_BLOOD01_N: string;
	BLOOD_WALL_BLOOD01_S: string;
	BLOOD_WALL_BLOOD01_W: string;
	BLOOD_WALL_BLOOD03_E: string;
	BLOOD_WALL_BLOOD03_N: string;
	BLOOD_WALL_BLOOD03_S: string;
	BLOOD_WALL_BLOOD03_W: string;
	BLOOD_WALL_BLOOD04_E: string;
	BLOOD_WALL_BLOOD04_N: string;
	BLOOD_WALL_BLOOD04_S: string;
	BLOOD_WALL_BLOOD04_W: string;
	BLOOD_WALL_BLOOD05_E: string;
	BLOOD_WALL_BLOOD05_N: string;
	BLOOD_WALL_BLOOD05_S: string;
	BLOOD_WALL_BLOOD05_W: string;
	BLOOD_WALL_BLOOD06_E: string;
	BLOOD_WALL_BLOOD06_N: string;
	BLOOD_WALL_BLOOD06_S: string;
	BLOOD_WALL_BLOOD06_W: string;
	BLOOD_WALL_BLOOD07_E: string;
	BLOOD_WALL_BLOOD07_N: string;
	BLOOD_WALL_BLOOD07_S: string;
	BLOOD_WALL_BLOOD07_W: string;
	BLOOD_WALL_BLOOD08_E: string;
	BLOOD_WALL_BLOOD08_N: string;
	BLOOD_WALL_BLOOD08_S: string;
	BLOOD_WALL_BLOOD08_W: string;
	BLOOD_WALL_BLOOD09_E: string;
	BLOOD_WALL_BLOOD09_N: string;
	BLOOD_WALL_BLOOD09_S: string;
	BLOOD_WALL_BLOOD09_W: string;
	BLOOD_WALL_BLOOD10_E: string;
	BLOOD_WALL_BLOOD10_N: string;
	BLOOD_WALL_BLOOD10_S: string;
	BLOOD_WALL_BLOOD10_W: string;
	BLOOD_WALL_BLOOD11_E: string;
	BLOOD_WALL_BLOOD11_N: string;
	BLOOD_WALL_BLOOD11_S: string;
	BLOOD_WALL_BLOOD11_W: string;
	BLOOD_WALL_BLOOD12_E: string;
	BLOOD_WALL_BLOOD12_N: string;
	BLOOD_WALL_BLOOD12_S: string;
	BLOOD_WALL_BLOOD12_W: string;
	BLOOD_WALL_BLOOD13_E: string;
	BLOOD_WALL_BLOOD13_N: string;
	BLOOD_WALL_BLOOD13_S: string;
	BLOOD_WALL_BLOOD13_W: string;
	BLOOD_WALL_BLOOD14_E: string;
	BLOOD_WALL_BLOOD14_N: string;
	BLOOD_WALL_BLOOD14_S: string;
	BLOOD_WALL_BLOOD14_W: string;
	BLOOD_WALL_BLOOD15_E: string;
	BLOOD_WALL_BLOOD15_N: string;
	BLOOD_WALL_BLOOD15_S: string;
	BLOOD_WALL_BLOOD15_W: string;
	BLOOD_WALL_BLOOD16_E: string;
	BLOOD_WALL_BLOOD16_N: string;
	BLOOD_WALL_BLOOD16_S: string;
	BLOOD_WALL_BLOOD16_W: string;
	BLOOD_WALL_BLOOD17_E: string;
	BLOOD_WALL_BLOOD17_N: string;
	BLOOD_WALL_BLOOD17_S: string;
	BLOOD_WALL_BLOOD17_W: string;
	BLOOD_WALL_BLOOD18_E: string;
	BLOOD_WALL_BLOOD18_N: string;
	BLOOD_WALL_BLOOD18_S: string;
	BLOOD_WALL_BLOOD18_W: string;
	BLOOD_WALL_OLD_BLOOD00: string;
	BLOOD_WALL_OLD_BLOOD01: string;
	BLOOD_WALL_OLD_BLOOD02: string;
	BLOOD_WALL_OLD_BLOOD03: string;
	BLOOD_WALL_OLD_BLOOD04: string;
	BLOOD_WALL_OLD_BLOOD05: string;
	BLOOD_WALL_OLD_BLOOD06: string;
	BLOOD_WALL_OLD_BLOOD07: string;
	BLOOD_WALL_OLD_BLOOD08: string;
	BLOOD_WALL_OLD_BLOOD09: string;
	CURSOR: string;
	CURSOR_GREEN: string;
	CURSOR_RED: string;
	ERROR: string;
	HALO_FRIENDLY: string;
	HALO_GD_NEUTRAL: string;
	HALO_NEUTRAL: string;
	HALO_SUMMONER: string;
	ICONS_ANIMATED_WEAPON: string;
	ICONS_BERSERK: string;
	ICONS_BLIND: string;
	ICONS_BOUND_SOUL: string;
	ICONS_CONSTRICTED: string;
	ICONS_CORRODED: string;
	ICONS_DEATHS_DOOR: string;
	ICONS_DEMON_PENTAGRAM1: string;
	ICONS_DEMON_PENTAGRAM2: string;
	ICONS_DEMON_PENTAGRAM3: string;
	ICONS_DEMON_PENTAGRAM4: string;
	ICONS_DEMON_PENTAGRAM5: string;
	ICONS_DRAIN: string;
	ICONS_FLEEING: string;
	ICONS_FRIENDLY: string;
	ICONS_GLOWING: string;
	ICONS_GOOD_NEUTRAL: string;
	ICONS_HASTED: string;
	ICONS_IDEALISED: string;
	ICONS_INFESTED: string;
	ICONS_INNER_FLAME: string;
	ICONS_MAY_STAB_BRAND: string;
	ICONS_MIGHT: string;
	ICONS_NEUTRAL: string;
	ICONS_NEW_STAIR: string;
	ICONS_NEW_TRANSPORTER: string;
	ICONS_PAIN_MIRROR: string;
	ICONS_PETRIFIED: string;
	ICONS_PETRIFYING: string;
	ICONS_PINNED: string;
	ICONS_POISON: string;
	ICONS_POSSESSABLE: string;
	ICONS_RECALL: string;
	ICONS_SLEEPING: string;
	ICONS_SLOWED: string;
	ICONS_SOMETHING_UNDER: string;
	ICONS_STICKY_FLAME: string;
	ICONS_SUMMONED: string;
	ICONS_SUMMONED_DURABLE: string;
	ICONS_SWIFT: string;
	ICONS_VILE_CLUTCH: string;
	LANDING: string;
	MAGICMAP: string;
	MASK_DEEP_WATER: string;
	MASK_DEEP_WATER_MURKY: string;
	MASK_DEEP_WATER_SHOALS: string;
	MASK_LAVA: string;
	MASK_SHALLOW_WATER: string;
	MASK_SHALLOW_WATER_MURKY: string;
	MASK_SHALLOW_WATER_SHOALS: string;
	MDAM_ALMOST_DEAD: string;
	MDAM_HEAVILY_DAMAGED: string;
	MDAM_LIGHTLY_DAMAGED: string;
	MDAM_MODERATELY_DAMAGED: string;
	MDAM_SEVERELY_DAMAGED: string;
	MOLD_GLOWING1: string;
	MOLD_GLOWING2: string;
	MOLD_GLOWING3: string;
	MOLD_GLOWING4: string;
	MOLD_SMALL1: string;
	MOLD_SMALL2: string;
	MOLD_SMALL3: string;
	MOLD_SMALL4: string;
	NUMBERS_MINUS1: string;
	NUMBERS_MINUS2: string;
	NUMBERS_MINUS3: string;
	NUMBERS_MINUS4: string;
	NUMBERS_MINUS5: string;
	NUMBERS_NUM0: string;
	NUMBERS_NUM1: string;
	NUMBERS_NUM2: string;
	NUMBERS_NUM3: string;
	NUMBERS_NUM4: string;
	NUMBERS_NUM5: string;
	NUMBERS_NUM6: string;
	NUMBERS_NUM7: string;
	NUMBERS_NUM8: string;
	NUMBERS_NUM9: string;
	NUMBERS_PLUS1: string;
	NUMBERS_PLUS2: string;
	NUMBERS_PLUS3: string;
	NUMBERS_PLUS4: string;
	NUMBERS_PLUS5: string;
	NUMBERS_ZERO: string;
	OUT_OF_RANGE: string;
	OUT_OF_SIGHT: string;
	RAY: string;
	RAY_MULTI: string;
	RAY_OUT_OF_RANGE: string;
	SENSED_MONSTER_EASY: string;
	SENSED_MONSTER_FRIENDLY: string;
	SENSED_MONSTER_NASTY: string;
	SENSED_MONSTER_TOUGH: string;
	SENSED_MONSTER_TRIVIAL: string;
	SLOT: string;
	SLOT_CURSED: string;
	SLOT_EQ: string;
	SLOT_EQ_CURSED: string;
	SLOT_VEHUMET: string;
	TODO: string;
	TRAVEL_EXCLUSION: string;
	TRAVEL_EXCLUSION_CENTRE: string;
	TRAVEL_PATH_FROM1: string;
	TRAVEL_PATH_FROM2: string;
	TRAVEL_PATH_FROM3: string;
	TRAVEL_PATH_FROM4: string;
	TRAVEL_PATH_FROM5: string;
	TRAVEL_PATH_FROM6: string;
	TRAVEL_PATH_FROM7: string;
	TRAVEL_PATH_FROM8: string;
	TRAVEL_PATH_TO1: string;
	TRAVEL_PATH_TO2: string;
	TRAVEL_PATH_TO3: string;
	TRAVEL_PATH_TO4: string;
	TRAVEL_PATH_TO5: string;
	TRAVEL_PATH_TO6: string;
	TRAVEL_PATH_TO7: string;
	TRAVEL_PATH_TO8: string;
	TUTORIAL_CURSOR: string;
	UNSEEN: string;
	UNSEEN_ARMOUR: string;
	UNSEEN_ITEM: string;
	UNSEEN_MONSTER: string;
	UNSEEN_WEAPON: string;
}

export const miscTiles: ImiscTiles = {
	BLOOD_GREEN: "misc/blood/blood_green.png",
	BLOOD_GREEN1: "misc/blood/blood_green1.png",
	BLOOD_GREEN2: "misc/blood/blood_green2.png",
	BLOOD_GREEN3: "misc/blood/blood_green3.png",
	BLOOD_GREEN4: "misc/blood/blood_green4.png",
	BLOOD_PUDDLE_RED: "misc/blood/blood_puddle_red.png",
	BLOOD_PUDDLE_RED1: "misc/blood/blood_puddle_red1.png",
	BLOOD_PUDDLE_RED2: "misc/blood/blood_puddle_red2.png",
	BLOOD_PUDDLE_RED3: "misc/blood/blood_puddle_red3.png",
	BLOOD_PUDDLE_RED4: "misc/blood/blood_puddle_red4.png",
	BLOOD_RED00: "misc/blood/blood_red00.png",
	BLOOD_RED01: "misc/blood/blood_red01.png",
	BLOOD_RED02: "misc/blood/blood_red02.png",
	BLOOD_RED03: "misc/blood/blood_red03.png",
	BLOOD_RED04: "misc/blood/blood_red04.png",
	BLOOD_RED05: "misc/blood/blood_red05.png",
	BLOOD_RED06: "misc/blood/blood_red06.png",
	BLOOD_RED07: "misc/blood/blood_red07.png",
	BLOOD_RED08: "misc/blood/blood_red08.png",
	BLOOD_RED09: "misc/blood/blood_red09.png",
	BLOOD_RED10: "misc/blood/blood_red10.png",
	BLOOD_RED11: "misc/blood/blood_red11.png",
	BLOOD_RED12: "misc/blood/blood_red12.png",
	BLOOD_RED13: "misc/blood/blood_red13.png",
	BLOOD_RED14: "misc/blood/blood_red14.png",
	BLOOD_RED15: "misc/blood/blood_red15.png",
	BLOOD_RED16: "misc/blood/blood_red16.png",
	BLOOD_RED17: "misc/blood/blood_red17.png",
	BLOOD_RED18: "misc/blood/blood_red18.png",
	BLOOD_RED19: "misc/blood/blood_red19.png",
	BLOOD_RED20: "misc/blood/blood_red20.png",
	BLOOD_RED21: "misc/blood/blood_red21.png",
	BLOOD_RED22: "misc/blood/blood_red22.png",
	BLOOD_RED23: "misc/blood/blood_red23.png",
	BLOOD_RED24: "misc/blood/blood_red24.png",
	BLOOD_RED25: "misc/blood/blood_red25.png",
	BLOOD_RED26: "misc/blood/blood_red26.png",
	BLOOD_RED27: "misc/blood/blood_red27.png",
	BLOOD_RED28: "misc/blood/blood_red28.png",
	BLOOD_RED29: "misc/blood/blood_red29.png",
	BLOOD_WALL_BLOOD00_E: "misc/blood/wall_blood00_e.png",
	BLOOD_WALL_BLOOD00_N: "misc/blood/wall_blood00_n.png",
	BLOOD_WALL_BLOOD00_S: "misc/blood/wall_blood00_s.png",
	BLOOD_WALL_BLOOD00_W: "misc/blood/wall_blood00_w.png",
	BLOOD_WALL_BLOOD01_E: "misc/blood/wall_blood01_e.png",
	BLOOD_WALL_BLOOD01_N: "misc/blood/wall_blood01_n.png",
	BLOOD_WALL_BLOOD01_S: "misc/blood/wall_blood01_s.png",
	BLOOD_WALL_BLOOD01_W: "misc/blood/wall_blood01_w.png",
	BLOOD_WALL_BLOOD03_E: "misc/blood/wall_blood03_e.png",
	BLOOD_WALL_BLOOD03_N: "misc/blood/wall_blood03_n.png",
	BLOOD_WALL_BLOOD03_S: "misc/blood/wall_blood03_s.png",
	BLOOD_WALL_BLOOD03_W: "misc/blood/wall_blood03_w.png",
	BLOOD_WALL_BLOOD04_E: "misc/blood/wall_blood04_e.png",
	BLOOD_WALL_BLOOD04_N: "misc/blood/wall_blood04_n.png",
	BLOOD_WALL_BLOOD04_S: "misc/blood/wall_blood04_s.png",
	BLOOD_WALL_BLOOD04_W: "misc/blood/wall_blood04_w.png",
	BLOOD_WALL_BLOOD05_E: "misc/blood/wall_blood05_e.png",
	BLOOD_WALL_BLOOD05_N: "misc/blood/wall_blood05_n.png",
	BLOOD_WALL_BLOOD05_S: "misc/blood/wall_blood05_s.png",
	BLOOD_WALL_BLOOD05_W: "misc/blood/wall_blood05_w.png",
	BLOOD_WALL_BLOOD06_E: "misc/blood/wall_blood06_e.png",
	BLOOD_WALL_BLOOD06_N: "misc/blood/wall_blood06_n.png",
	BLOOD_WALL_BLOOD06_S: "misc/blood/wall_blood06_s.png",
	BLOOD_WALL_BLOOD06_W: "misc/blood/wall_blood06_w.png",
	BLOOD_WALL_BLOOD07_E: "misc/blood/wall_blood07_e.png",
	BLOOD_WALL_BLOOD07_N: "misc/blood/wall_blood07_n.png",
	BLOOD_WALL_BLOOD07_S: "misc/blood/wall_blood07_s.png",
	BLOOD_WALL_BLOOD07_W: "misc/blood/wall_blood07_w.png",
	BLOOD_WALL_BLOOD08_E: "misc/blood/wall_blood08_e.png",
	BLOOD_WALL_BLOOD08_N: "misc/blood/wall_blood08_n.png",
	BLOOD_WALL_BLOOD08_S: "misc/blood/wall_blood08_s.png",
	BLOOD_WALL_BLOOD08_W: "misc/blood/wall_blood08_w.png",
	BLOOD_WALL_BLOOD09_E: "misc/blood/wall_blood09_e.png",
	BLOOD_WALL_BLOOD09_N: "misc/blood/wall_blood09_n.png",
	BLOOD_WALL_BLOOD09_S: "misc/blood/wall_blood09_s.png",
	BLOOD_WALL_BLOOD09_W: "misc/blood/wall_blood09_w.png",
	BLOOD_WALL_BLOOD10_E: "misc/blood/wall_blood10_e.png",
	BLOOD_WALL_BLOOD10_N: "misc/blood/wall_blood10_n.png",
	BLOOD_WALL_BLOOD10_S: "misc/blood/wall_blood10_s.png",
	BLOOD_WALL_BLOOD10_W: "misc/blood/wall_blood10_w.png",
	BLOOD_WALL_BLOOD11_E: "misc/blood/wall_blood11_e.png",
	BLOOD_WALL_BLOOD11_N: "misc/blood/wall_blood11_n.png",
	BLOOD_WALL_BLOOD11_S: "misc/blood/wall_blood11_s.png",
	BLOOD_WALL_BLOOD11_W: "misc/blood/wall_blood11_w.png",
	BLOOD_WALL_BLOOD12_E: "misc/blood/wall_blood12_e.png",
	BLOOD_WALL_BLOOD12_N: "misc/blood/wall_blood12_n.png",
	BLOOD_WALL_BLOOD12_S: "misc/blood/wall_blood12_s.png",
	BLOOD_WALL_BLOOD12_W: "misc/blood/wall_blood12_w.png",
	BLOOD_WALL_BLOOD13_E: "misc/blood/wall_blood13_e.png",
	BLOOD_WALL_BLOOD13_N: "misc/blood/wall_blood13_n.png",
	BLOOD_WALL_BLOOD13_S: "misc/blood/wall_blood13_s.png",
	BLOOD_WALL_BLOOD13_W: "misc/blood/wall_blood13_w.png",
	BLOOD_WALL_BLOOD14_E: "misc/blood/wall_blood14_e.png",
	BLOOD_WALL_BLOOD14_N: "misc/blood/wall_blood14_n.png",
	BLOOD_WALL_BLOOD14_S: "misc/blood/wall_blood14_s.png",
	BLOOD_WALL_BLOOD14_W: "misc/blood/wall_blood14_w.png",
	BLOOD_WALL_BLOOD15_E: "misc/blood/wall_blood15_e.png",
	BLOOD_WALL_BLOOD15_N: "misc/blood/wall_blood15_n.png",
	BLOOD_WALL_BLOOD15_S: "misc/blood/wall_blood15_s.png",
	BLOOD_WALL_BLOOD15_W: "misc/blood/wall_blood15_w.png",
	BLOOD_WALL_BLOOD16_E: "misc/blood/wall_blood16_e.png",
	BLOOD_WALL_BLOOD16_N: "misc/blood/wall_blood16_n.png",
	BLOOD_WALL_BLOOD16_S: "misc/blood/wall_blood16_s.png",
	BLOOD_WALL_BLOOD16_W: "misc/blood/wall_blood16_w.png",
	BLOOD_WALL_BLOOD17_E: "misc/blood/wall_blood17_e.png",
	BLOOD_WALL_BLOOD17_N: "misc/blood/wall_blood17_n.png",
	BLOOD_WALL_BLOOD17_S: "misc/blood/wall_blood17_s.png",
	BLOOD_WALL_BLOOD17_W: "misc/blood/wall_blood17_w.png",
	BLOOD_WALL_BLOOD18_E: "misc/blood/wall_blood18_e.png",
	BLOOD_WALL_BLOOD18_N: "misc/blood/wall_blood18_n.png",
	BLOOD_WALL_BLOOD18_S: "misc/blood/wall_blood18_s.png",
	BLOOD_WALL_BLOOD18_W: "misc/blood/wall_blood18_w.png",
	BLOOD_WALL_OLD_BLOOD00: "misc/blood/wall_old_blood00.png",
	BLOOD_WALL_OLD_BLOOD01: "misc/blood/wall_old_blood01.png",
	BLOOD_WALL_OLD_BLOOD02: "misc/blood/wall_old_blood02.png",
	BLOOD_WALL_OLD_BLOOD03: "misc/blood/wall_old_blood03.png",
	BLOOD_WALL_OLD_BLOOD04: "misc/blood/wall_old_blood04.png",
	BLOOD_WALL_OLD_BLOOD05: "misc/blood/wall_old_blood05.png",
	BLOOD_WALL_OLD_BLOOD06: "misc/blood/wall_old_blood06.png",
	BLOOD_WALL_OLD_BLOOD07: "misc/blood/wall_old_blood07.png",
	BLOOD_WALL_OLD_BLOOD08: "misc/blood/wall_old_blood08.png",
	BLOOD_WALL_OLD_BLOOD09: "misc/blood/wall_old_blood09.png",
	CURSOR: "misc/cursor.png",
	CURSOR_GREEN: "misc/cursor_green.png",
	CURSOR_RED: "misc/cursor_red.png",
	ERROR: "misc/error.png",
	HALO_FRIENDLY: "misc/halo_friendly.png",
	HALO_GD_NEUTRAL: "misc/halo_gd_neutral.png",
	HALO_NEUTRAL: "misc/halo_neutral.png",
	HALO_SUMMONER: "misc/halo_summoner.png",
	ICONS_ANIMATED_WEAPON: "misc/icons/animated_weapon.png",
	ICONS_BERSERK: "misc/icons/berserk.png",
	ICONS_BLIND: "misc/icons/blind.png",
	ICONS_BOUND_SOUL: "misc/icons/bound_soul.png",
	ICONS_CONSTRICTED: "misc/icons/constricted.png",
	ICONS_CORRODED: "misc/icons/corroded.png",
	ICONS_DEATHS_DOOR: "misc/icons/deaths_door.png",
	ICONS_DEMON_PENTAGRAM1: "misc/icons/demon_pentagram1.png",
	ICONS_DEMON_PENTAGRAM2: "misc/icons/demon_pentagram2.png",
	ICONS_DEMON_PENTAGRAM3: "misc/icons/demon_pentagram3.png",
	ICONS_DEMON_PENTAGRAM4: "misc/icons/demon_pentagram4.png",
	ICONS_DEMON_PENTAGRAM5: "misc/icons/demon_pentagram5.png",
	ICONS_DRAIN: "misc/icons/drain.png",
	ICONS_FLEEING: "misc/icons/fleeing.png",
	ICONS_FRIENDLY: "misc/icons/friendly.png",
	ICONS_GLOWING: "misc/icons/glowing.png",
	ICONS_GOOD_NEUTRAL: "misc/icons/good_neutral.png",
	ICONS_HASTED: "misc/icons/hasted.png",
	ICONS_IDEALISED: "misc/icons/idealised.png",
	ICONS_INFESTED: "misc/icons/infested.png",
	ICONS_INNER_FLAME: "misc/icons/inner_flame.png",
	ICONS_MAY_STAB_BRAND: "misc/icons/may_stab_brand.png",
	ICONS_MIGHT: "misc/icons/might.png",
	ICONS_NEUTRAL: "misc/icons/neutral.png",
	ICONS_NEW_STAIR: "misc/icons/new_stair.png",
	ICONS_NEW_TRANSPORTER: "misc/icons/new_transporter.png",
	ICONS_PAIN_MIRROR: "misc/icons/pain_mirror.png",
	ICONS_PETRIFIED: "misc/icons/petrified.png",
	ICONS_PETRIFYING: "misc/icons/petrifying.png",
	ICONS_PINNED: "misc/icons/pinned.png",
	ICONS_POISON: "misc/icons/poison.png",
	ICONS_POSSESSABLE: "misc/icons/possessable.png",
	ICONS_RECALL: "misc/icons/recall.png",
	ICONS_SLEEPING: "misc/icons/sleeping.png",
	ICONS_SLOWED: "misc/icons/slowed.png",
	ICONS_SOMETHING_UNDER: "misc/icons/something_under.png",
	ICONS_STICKY_FLAME: "misc/icons/sticky_flame.png",
	ICONS_SUMMONED: "misc/icons/summoned.png",
	ICONS_SUMMONED_DURABLE: "misc/icons/summoned_durable.png",
	ICONS_SWIFT: "misc/icons/swift.png",
	ICONS_VILE_CLUTCH: "misc/icons/vile_clutch.png",
	LANDING: "misc/landing.png",
	MAGICMAP: "misc/magicmap.png",
	MASK_DEEP_WATER: "misc/mask_deep_water.png",
	MASK_DEEP_WATER_MURKY: "misc/mask_deep_water_murky.png",
	MASK_DEEP_WATER_SHOALS: "misc/mask_deep_water_shoals.png",
	MASK_LAVA: "misc/mask_lava.png",
	MASK_SHALLOW_WATER: "misc/mask_shallow_water.png",
	MASK_SHALLOW_WATER_MURKY: "misc/mask_shallow_water_murky.png",
	MASK_SHALLOW_WATER_SHOALS: "misc/mask_shallow_water_shoals.png",
	MDAM_ALMOST_DEAD: "misc/mdam_almost_dead.png",
	MDAM_HEAVILY_DAMAGED: "misc/mdam_heavily_damaged.png",
	MDAM_LIGHTLY_DAMAGED: "misc/mdam_lightly_damaged.png",
	MDAM_MODERATELY_DAMAGED: "misc/mdam_moderately_damaged.png",
	MDAM_SEVERELY_DAMAGED: "misc/mdam_severely_damaged.png",
	MOLD_GLOWING1: "misc/mold_glowing1.png",
	MOLD_GLOWING2: "misc/mold_glowing2.png",
	MOLD_GLOWING3: "misc/mold_glowing3.png",
	MOLD_GLOWING4: "misc/mold_glowing4.png",
	MOLD_SMALL1: "misc/mold_small1.png",
	MOLD_SMALL2: "misc/mold_small2.png",
	MOLD_SMALL3: "misc/mold_small3.png",
	MOLD_SMALL4: "misc/mold_small4.png",
	NUMBERS_MINUS1: "misc/numbers/minus1.png",
	NUMBERS_MINUS2: "misc/numbers/minus2.png",
	NUMBERS_MINUS3: "misc/numbers/minus3.png",
	NUMBERS_MINUS4: "misc/numbers/minus4.png",
	NUMBERS_MINUS5: "misc/numbers/minus5.png",
	NUMBERS_NUM0: "misc/numbers/num0.png",
	NUMBERS_NUM1: "misc/numbers/num1.png",
	NUMBERS_NUM2: "misc/numbers/num2.png",
	NUMBERS_NUM3: "misc/numbers/num3.png",
	NUMBERS_NUM4: "misc/numbers/num4.png",
	NUMBERS_NUM5: "misc/numbers/num5.png",
	NUMBERS_NUM6: "misc/numbers/num6.png",
	NUMBERS_NUM7: "misc/numbers/num7.png",
	NUMBERS_NUM8: "misc/numbers/num8.png",
	NUMBERS_NUM9: "misc/numbers/num9.png",
	NUMBERS_PLUS1: "misc/numbers/plus1.png",
	NUMBERS_PLUS2: "misc/numbers/plus2.png",
	NUMBERS_PLUS3: "misc/numbers/plus3.png",
	NUMBERS_PLUS4: "misc/numbers/plus4.png",
	NUMBERS_PLUS5: "misc/numbers/plus5.png",
	NUMBERS_ZERO: "misc/numbers/zero.png",
	OUT_OF_RANGE: "misc/out_of_range.png",
	OUT_OF_SIGHT: "misc/out_of_sight.png",
	RAY: "misc/ray.png",
	RAY_MULTI: "misc/ray_multi.png",
	RAY_OUT_OF_RANGE: "misc/ray_out_of_range.png",
	SENSED_MONSTER_EASY: "misc/sensed_monster_easy.png",
	SENSED_MONSTER_FRIENDLY: "misc/sensed_monster_friendly.png",
	SENSED_MONSTER_NASTY: "misc/sensed_monster_nasty.png",
	SENSED_MONSTER_TOUGH: "misc/sensed_monster_tough.png",
	SENSED_MONSTER_TRIVIAL: "misc/sensed_monster_trivial.png",
	SLOT: "misc/slot.png",
	SLOT_CURSED: "misc/slot_cursed.png",
	SLOT_EQ: "misc/slot_eq.png",
	SLOT_EQ_CURSED: "misc/slot_eq_cursed.png",
	SLOT_VEHUMET: "misc/slot_vehumet.png",
	TODO: "misc/todo.png",
	TRAVEL_EXCLUSION: "misc/travel_exclusion.png",
	TRAVEL_EXCLUSION_CENTRE: "misc/travel_exclusion_centre.png",
	TRAVEL_PATH_FROM1: "misc/travel_path_from1.png",
	TRAVEL_PATH_FROM2: "misc/travel_path_from2.png",
	TRAVEL_PATH_FROM3: "misc/travel_path_from3.png",
	TRAVEL_PATH_FROM4: "misc/travel_path_from4.png",
	TRAVEL_PATH_FROM5: "misc/travel_path_from5.png",
	TRAVEL_PATH_FROM6: "misc/travel_path_from6.png",
	TRAVEL_PATH_FROM7: "misc/travel_path_from7.png",
	TRAVEL_PATH_FROM8: "misc/travel_path_from8.png",
	TRAVEL_PATH_TO1: "misc/travel_path_to1.png",
	TRAVEL_PATH_TO2: "misc/travel_path_to2.png",
	TRAVEL_PATH_TO3: "misc/travel_path_to3.png",
	TRAVEL_PATH_TO4: "misc/travel_path_to4.png",
	TRAVEL_PATH_TO5: "misc/travel_path_to5.png",
	TRAVEL_PATH_TO6: "misc/travel_path_to6.png",
	TRAVEL_PATH_TO7: "misc/travel_path_to7.png",
	TRAVEL_PATH_TO8: "misc/travel_path_to8.png",
	TUTORIAL_CURSOR: "misc/tutorial_cursor.png",
	UNSEEN: "misc/unseen.png",
	UNSEEN_ARMOUR: "misc/unseen_armour.png",
	UNSEEN_ITEM: "misc/unseen_item.png",
	UNSEEN_MONSTER: "misc/unseen_monster.png",
	UNSEEN_WEAPON: "misc/unseen_weapon.png",
};